<?php
$lang = $_SESSION['lang'] ?? 'en';

$translations = [
    // General
    'admin_dashboard' => ['en' => 'Admin Dashboard', 'ar' => 'لوحة تحكم المسؤول'],
    'manage_account' => ['en' => 'Manage Account', 'ar' => 'إدارة الحساب'],
    'admin_name' => ['en' => 'Admin Name', 'ar' => 'اسم المسؤول'],
    'email' => ['en' => 'Email', 'ar' => 'البريد الإلكتروني'],
    'update_info' => ['en' => 'Update Info', 'ar' => 'تحديث المعلومات'],
    'delete_my_account' => ['en' => 'Delete My Account', 'ar' => 'حذف حسابي'],
    'all_rights_reserved' => ['en' => 'All rights reserved.', 'ar' => 'جميع الحقوق محفوظة.'],
    'admin_settings' => ['en' => 'Admin Settings', 'ar' => 'إعدادات المسؤول'],
    'admin_categories' => ['en' => 'Manage Categories', 'ar' => 'إدارة الفئات'],
    'admin_comments' => ['en' => 'Manage Comments', 'ar' => 'إدارة التعليقات'],
    'admin_companies' => ['en' => 'Manage Companies', 'ar' => 'إدارة الشركات'],
    'admin_users' => ['en' => 'Manage Users', 'ar' => 'إدارة المستخدمين'],
    'admin_products' => ['en' => 'Manage Products', 'ar' => 'إدارة المنتجات'],
    'admin_admins' => ['en' => 'Manage Admin', 'ar' => 'إدارة المسؤولين'],
    'admin_reports' => ['en' => 'Manage Reports', 'ar' => 'إدارة التقارير'],
    'search_product' => ['en' => 'Search for a product...','ar' => 'ابحث عن منتج...',],


    'subscription_successful' => ['en' => 'You have successfully subscribed!', 'ar' => 'تم الاشتراك بنجاح!'],
'subscription_failed' => ['en' => 'Failed to subscribe. Please try again later.', 'ar' => 'فشل الاشتراك. حاول لاحقاً.'],
'invalid_email' => ['en' => 'Please enter a valid email address.', 'ar' => 'يرجى إدخال بريد إلكتروني صالح.'],



    'policies' => ['en' => 'Policies', 'ar' => 'السياسات'],
    'guidelines' => ['en' => 'Guidelines', 'ar' => 'الإرشادات'],
    'privacy_policy' => ['en' => 'Privacy Policy', 'ar' => 'سياسة الخصوصية'],
    'terms_of_service' => ['en' => 'Terms of Service', 'ar' => 'شروط الاستخدام'],
    'content_policy' => ['en' => 'Content & Review Policy', 'ar' => 'سياسة المحتوى والمراجعات'],
    'reward_policy' => ['en' => 'Reward & Badge Policy', 'ar' => 'سياسة النقاط والشارات'],
    'reporting_policy' => ['en' => 'Reporting & Moderation', 'ar' => 'سياسة الإبلاغ والإشراف'],
    'action' => ['en' => 'Action', 'ar' => 'الإجراء'],
    'regular_product' => ['en' => 'Regular Product', 'ar' => 'منتج عادي'],
    'local_product' => ['en' => 'Local Jordanian Product', 'ar' => 'منتج أردني محلي'],
    'submit_review' => ['en' => 'Submit a Product Review', 'ar' => 'إضافة مراجعة منتج'],
    'post_comment' => ['en' => 'Post a Comment', 'ar' => 'نشر تعليق'],
    'receive_like' => ['en' => 'Receive a Like', 'ar' => 'الحصول على إعجاب'],

    'faq_page_title' => ['en' => 'FAQ','ar' => 'الأسئلة الشائعة'],

    'faq_title' => ['en' => 'Frequently Asked Questions', 'ar' => 'الأسئلة الشائعة'],
    'faq_register' => ['en' => 'How do I register for a BuyWise account?', 'ar' => 'كيف يمكنني التسجيل في BuyWise؟'],
    'faq_register_ans' => ['en' => 'Click on "Sign Up", select your role (User or Company), fill in the registration form, and verify your email address using the link sent to you.', 'ar' => 'انقر على "التسجيل"، اختر نوع الحساب (مستخدم أو شركة)، املأ النموذج، وفعّل بريدك الإلكتروني عبر الرابط المُرسل.'],

    'faq_no_verification' => ['en' => 'I didn’t receive my email verification. What should I do?', 'ar' => 'لم أستلم رسالة التحقق من البريد الإلكتروني. ماذا أفعل؟'],
    'faq_no_verification_ans' => ['en' => 'Check your spam or junk folder. If not found, click "Resend Verification" or contact BuyWise via Email.', 'ar' => 'تحقق من مجلد الرسائل غير المرغوب فيها. إذا لم تجدها، اضغط "إعادة إرسال رمز التحقق" أو تواصل مع الدعم.'],

    'faq_reset_password' => ['en' => 'How can I reset my password?', 'ar' => 'كيف يمكنني إعادة تعيين كلمة المرور؟'],
    'faq_reset_password_ans' => ['en' => 'Click "Forgot Password" and follow the email instructions to reset it securely.', 'ar' => 'اضغط على "نسيت كلمة المرور" واتبع التعليمات المرسلة إلى بريدك الإلكتروني.'],

    'faq_add_product' => ['en' => 'How do I add a product as a user or company?', 'ar' => 'كيف يمكنني إضافة منتج كمستخدم أو شركة؟'],
    'faq_add_product_ans' => ['en' => 'Go to your Dashboard, select "Add Product", fill the form and upload the image. Admin will review it before publishing.', 'ar' => 'انتقل إلى لوحة التحكم، اختر "إضافة منتج"، املأ النموذج وارفع الصورة. سيتم مراجعتها من قبل الإدارة.'],

    'faq_badges' => ['en' => 'What do “Authentic” and “Fake” review badges mean?', 'ar' => 'ما معنى شارات "أصلي" و"مزيف"؟'],
    'faq_badges_ans' => ['en' => 'These badges are generated by AI to indicate review authenticity based on content analysis.', 'ar' => 'يتم توليد هذه الشارات بواسطة الذكاء الاصطناعي لتحديد مدى مصداقية المراجعة.'],

    'faq_points' => ['en' => 'How can I earn points and badges on BuyWise?', 'ar' => 'كيف يمكنني كسب النقاط والشارات في BuyWise؟'],
    'faq_points_ans' => ['en' => 'Earn points by reviewing, commenting, and receiving likes. Local reviews get double points. Your badge level increases automatically.', 'ar' => 'اكسب النقاط من خلال المراجعات، التعليقات، والإعجابات. المنتجات المحلية تمنح نقاطًا مضاعفة. يتم تحديث مستوى الشارة تلقائيًا.'],

    'faq_rewards' => ['en' => 'What are company-sponsored rewards?', 'ar' => 'ما هي المكافآت المقدمة من الشركات؟'],
    'faq_rewards_ans' => ['en' => 'Companies offer vouchers or discounts to active users. You can claim these under "My Vouchers".', 'ar' => 'تقدم الشركات قسائم أو خصومات للمستخدمين النشطين. يمكنك المطالبة بها ضمن "قسائمي".'],

    'faq_interaction' => ['en' => 'Can I interact with other users\' reviews?', 'ar' => 'هل يمكنني التفاعل مع مراجعات المستخدمين الآخرين؟'],
    'faq_interaction_ans' => ['en' => 'Yes, you can like, reply, and report. Positive interaction boosts your credibility and points.', 'ar' => 'نعم، يمكنك الإعجاب، الرد، والإبلاغ. التفاعل الإيجابي يعزز مصداقيتك ويزيد نقاطك.'],

    'faq_report' => ['en' => 'How does the reporting system work?', 'ar' => 'كيف يعمل نظام الإبلاغ؟'],
    'faq_report_ans' => ['en' => 'Report inappropriate content by selecting a reason. Our team reviews and acts accordingly.', 'ar' => 'قم بالإبلاغ عن المحتوى غير المناسب باختيار سبب. يقوم فريقنا بالمراجعة واتخاذ الإجراء اللازم.'],

    'faq_languages' => ['en' => 'Is BuyWise available in multiple languages?', 'ar' => 'هل BuyWise متاح بعدة لغات؟'],
    'faq_languages_ans' => ['en' => 'Yes, it supports English and Arabic. Use the switcher at the top of the page.', 'ar' => 'نعم، يدعم الإنجليزية والعربية. استخدم أداة التبديل في أعلى الصفحة.'],

    'faq_notifications' => ['en' => 'How do notifications work on BuyWise?', 'ar' => 'كيف تعمل الإشعارات في BuyWise؟'],
    'faq_notifications_ans' => ['en' => 'You’ll get notified for replies, likes, rewards, and admin actions via the bell icon.', 'ar' => 'سوف تتلقى إشعارات بالردود، الإعجابات، المكافآت، وإجراءات الإدارة من خلال رمز الجرس.'],

    'faq_profile_visibility' => ['en' => 'Are user profiles visible to others?', 'ar' => 'هل يمكن للآخرين رؤية ملفي الشخصي؟'],
    'faq_profile_visibility_ans' => ['en' => 'Yes, public profiles show your reviews and badges, but private info like email is hidden.', 'ar' => 'نعم، تُظهر الملفات العامة مراجعاتك وشاراتك، لكن تبقى معلوماتك الخاصة مثل البريد الإلكتروني مخفية.'],

    'faq_account_update' => ['en' => 'How do I update or delete my BuyWise account?', 'ar' => 'كيف يمكنني تحديث أو حذف حسابي في BuyWise؟'],
    'faq_account_update_ans' => ['en' => 'Go to “Account Settings” in your dashboard to update details or permanently delete your account.', 'ar' => 'انتقل إلى "إعدادات الحساب" في لوحة التحكم لتحديث بياناتك أو حذف الحساب نهائيًا.'],

// --- Badge Levels
'badge_levels_intro' => [
    'en' => 'As you earn points, your badge level automatically increases to reflect your contributions:',
    'ar' => 'مع كسبك للنقاط، يتم ترقية شارتك تلقائيًا لتعكس مدى مساهمتك في المنصة:'
],

// Policy Descriptions
'privacy_policy_desc' => [
    'en' => 'BuyWise respects your privacy. We collect only necessary information such as your name, email, and account type to offer a secure and personalized experience. Your data is stored securely and never shared without consent. Users can request to view, update, or delete their personal data at any time.',
    'ar' => 'تحترم BuyWise خصوصيتك. نقوم بجمع المعلومات الضرورية فقط مثل الاسم والبريد الإلكتروني ونوع الحساب لتقديم تجربة آمنة وشخصية. يتم تخزين بياناتك بشكل آمن ولا يتم مشاركتها دون موافقتك. يمكن للمستخدمين طلب عرض أو تحديث أو حذف بياناتهم الشخصية في أي وقت.'
],

'terms_of_service_desc' => [
    'en' => 'By using BuyWise, you agree to follow our usage terms. These include respecting others, avoiding spam or abuse, and posting only relevant and authentic content. BuyWise reserves the right to suspend or delete accounts that violate these terms.',
    'ar' => 'باستخدامك لمنصة BuyWise، فإنك توافق على الالتزام بشروط الاستخدام لدينا، والتي تشمل احترام الآخرين، وتجنب الرسائل المزعجة أو الإساءة، ونشر محتوى أصلي وملائم فقط. تحتفظ BuyWise بالحق في تعليق أو حذف الحسابات التي تنتهك هذه الشروط.'
],

'content_policy_desc' => [
    'en' => 'We maintain high standards for content quality. All reviews must be authentic, respectful, and based on personal experience. Promotional spam, fake content, hate speech, or irrelevant comments are prohibited and may be removed by our moderators or flagged by our AI detection system.',
    'ar' => 'نلتزم بمعايير عالية لجودة المحتوى. يجب أن تكون جميع المراجعات أصلية، محترمة، ومبنية على تجربة شخصية. يُمنع نشر الرسائل الدعائية، المحتوى المزيف، خطاب الكراهية، أو التعليقات غير الملائمة، وقد تتم إزالتها من قبل المشرفين أو تمييزها بواسطة نظام الكشف الذكي لدينا.'
],

'reward_policy_intro' => [
    'en' => 'BuyWise uses a point-based system to recognize and reward user contributions. Points are awarded for meaningful engagement such as reviewing products, commenting, and receiving likes.',
    'ar' => 'تعتمد BuyWise على نظام نقاط لمكافأة مساهمات المستخدمين. يتم منح النقاط للمشاركات المفيدة مثل مراجعة المنتجات، التعليق، وتلقي الإعجابات.'
],

'user_badges_desc' => [
    'en' => 'As you earn points, your badge level automatically increases to reflect your contributions:',
    'ar' => 'كلما زادت نقاطك، يرتفع مستوى الشارة تلقائيًا ليعكس مساهماتك:'
],

'badge_normal_range' => [
    'en' => '0 to 499 points',
    'ar' => 'من 0 إلى 499 نقطة'
],
'badge_professional_range' => [
    'en' => '500 to 1499 points',
    'ar' => 'من 500 إلى 1499 نقطة'
],
'badge_expert_range' => [
    'en' => '1500 to 4999 points',
    'ar' => 'من 1500 إلى 4999 نقطة'
],
'badge_legend_range' => [
    'en' => '5000+ points',
    'ar' => '5000 نقطة فما فوق'
],
'points_system' => [
  'en' => 'Points System',
  'ar' => 'نظام النقاط'
],
'how_points_work' => [
  'en' => 'How Do You Earn Points?',
  'ar' => 'كيف تربح النقاط؟'
],
'points_explanation_text' => [
  'en' => 'Users earn points by reviewing products, commenting, and receiving likes. Points vary based on product type.',
  'ar' => 'يمكنك جمع النقاط من خلال كتابة المراجعات، التعليق، والحصول على إعجابات. تختلف النقاط حسب نوع المنتج.'
],
'badges_based_on_points' => [
  'en' => 'Badges Based on Points',
  'ar' => 'الرتب حسب عدد النقاط'
],


'company_rewards_desc' => [
    'en' => 'Companies can offer rewards (e.g., vouchers or discounts) to users who engage with their products. Eligible users can view and claim these in the “My Vouchers” tab under their dashboard. Availability and requirements may vary by company.',
    'ar' => 'يمكن للشركات تقديم مكافآت (مثل القسائم أو الخصومات) للمستخدمين الذين يتفاعلون مع منتجاتهم. يمكن للمستخدمين المؤهلين عرض هذه المكافآت والمطالبة بها من خلال تبويب "قسائمي" في لوحة التحكم. قد تختلف الشروط والتوفر حسب كل شركة.'
],

'track_progress_desc' => [
    'en' => 'To see your total points and current badge, visit your',
    'ar' => 'لمعرفة مجموع نقاطك والشارة الحالية، قم بزيارة'
],

'reporting_policy_desc' => [
    'en' => 'Users can report content that violates our policies. Every report is reviewed manually. Verified violations may lead to warnings, content removal, or account suspension. Repeated offenses can result in permanent bans to maintain platform integrity.',
    'ar' => 'يمكن للمستخدمين الإبلاغ عن المحتوى الذي ينتهك سياساتنا. تتم مراجعة كل بلاغ يدويًا. وقد تؤدي الانتهاكات المثبتة إلى إنذارات، أو حذف المحتوى، أو تعليق الحساب. التكرار قد يؤدي إلى الحظر الدائم للحفاظ على نزاهة المنصة.'
],

'how_points_earned' => [
    'en' => 'How are points earned on BuyWise?',
    'ar' => 'كيف يتم كسب النقاط على BuyWise؟'
],

'user_badges' => [
    'en' => 'What are the badge levels and what do they mean?',
    'ar' => 'ما هي مستويات الشارات وما معناها؟'
],

'company_rewards' => [
    'en' => 'How do company rewards work?',
    'ar' => 'كيف تعمل مكافآت الشركات؟'
],

'track_progress' => [
    'en' => 'Where can I track my points and badge progress?',
    'ar' => 'أين يمكنني تتبع نقاطي وتقدمي في الشارات؟'
],

    // Dashboard
    'dashboard' => ['en' => 'Dashboard', 'ar' => 'لوحة التحكم'],
    'welcome' => ['en' => 'Welcome', 'ar' => 'مرحباً'],
    'dashboard_intro' => ['en' => 'This is your administrator control panel.', 'ar' => 'هذه لوحة التحكم الخاصة بالمسؤول.'],

    // Roles
    'admin' => ['en' => 'Admin', 'ar' => 'مسؤول'],
    'controls' => ['en' => 'Controls', 'ar' => 'التحكم'],

    // Misc
    'unknown_admin' => ['en' => 'Unknown Admin', 'ar' => 'مسؤول غير معروف'],

    'active_categories'   => ['en' => 'Active Categories', 'ar' => 'الفئات المفعلة'],
'inactive_categories' => ['en' => 'Inactive Categories', 'ar' => 'الفئات غير المفعلة'],
'total_categories'    => ['en' => 'Total Categories', 'ar' => 'إجمالي الفئات'],
'delete_category'    => ['en' => 'Delete Category', 'ar' => 'حذف الفئة'],

'confirm_activate_category' => [
    'en' => 'Are you sure you want to activate this category?',
    'ar' => 'هل أنت متأكد أنك تريد تفعيل هذه الفئة؟'
],
'confirm_deactivate_category' => [
    'en' => 'Are you sure you want to deactivate this category?',
    'ar' => 'هل أنت متأكد أنك تريد تعطيل هذه الفئة؟'
],
'confirm_delete_category' => [
    'en' => 'Are you sure you want to delete this category?',
    'ar' => 'هل أنت متأكد أنك تريد حذف هذه الفئة؟'
],
'status_updated' => [
    'en' => 'Category status updated successfully.',
    'ar' => 'تم تحديث حالة الفئة بنجاح.'
],
'category_deleted' => [
    'en' => 'Category deleted successfully.',
    'ar' => 'تم حذف الفئة بنجاح.'
],
'delete_failed' => [
    'en' => 'Failed to delete the category.',
    'ar' => 'فشل في حذف الفئة.'
],
'update_failed' => [
    'en' => 'Failed to update the category status.',
    'ar' => 'فشل في تحديث حالة الفئة.'
],
'confirm_reject_user_product' => [
    'en' => 'Are you sure you want to reject this product?',
    'ar' => 'هل أنت متأكد من رفض هذا المنتج؟'
],


    // Password
    'password_info' => [
        'en' => 'To update your password, fill all fields below.',
        'ar' => 'لتحديث كلمة المرور، يرجى تعبئة جميع الحقول أدناه.'
    ],
    'current_password' => ['en' => 'Current Password', 'ar' => 'كلمة المرور الحالية'],
    'new_password' => ['en' => 'New Password', 'ar' => 'كلمة المرور الجديدة'],
    'confirm_password' => ['en' => 'Confirm Password', 'ar' => 'تأكيد كلمة المرور'],

    // Alerts / Errors
    'admin_not_found' => ['en' => 'Admin account not found.', 'ar' => 'حساب المشرف غير موجود.'],
    'email_in_use' => ['en' => 'This email is already in use.', 'ar' => 'هذا البريد الإلكتروني مستخدم بالفعل.'],
    'current_password_required' => ['en' => 'Current password is required.', 'ar' => 'كلمة المرور الحالية مطلوبة.'],
    'incorrect_current_password' => ['en' => 'Current password is incorrect.', 'ar' => 'كلمة المرور الحالية غير صحيحة.'],
    'passwords_do_not_match' => ['en' => 'New password and confirmation do not match.', 'ar' => 'كلمة المرور وتأكيدها غير متطابقين.'],
    'update_failed' => ['en' => 'Update failed', 'ar' => 'فشل في التحديث'],
    'info_updated' => ['en' => 'Information updated successfully.', 'ar' => 'تم تحديث المعلومات بنجاح.'],
    'account_deleted' => ['en' => 'Your account has been deleted.', 'ar' => 'تم حذف حسابك.'],
    'password_updated_login_again' => ['en' => 'Password updated successfully. Please login again.', 'ar' => 'تم تحديث كلمة المرور بنجاح. يرجى تسجيل الدخول مرة أخرى.'],

    // JS / Popup
    'confirm_delete_account' => ['en' => 'Are you sure you want to delete your account?', 'ar' => 'هل أنت متأكد أنك تريد حذف حسابك؟'],
    'manage_admins' => ['en' => 'Manage Admins', 'ar' => 'إدارة المسؤولين'],
    'add_new_admin' => ['en' => 'Add New Admin', 'ar' => 'إضافة مشرف جديد'],
    'password' => ['en' => 'Password', 'ar' => 'كلمة المرور'],
    'add_admin' => ['en' => 'Add Admin', 'ar' => 'إضافة مسؤول'],
    'all_admins' => ['en' => 'All Admins', 'ar' => 'جميع المسؤولين'],
    'created_at' => ['en' => 'Created At', 'ar' => 'تاريخ الإنشاء'],
    'actions' => ['en' => 'Actions', 'ar' => 'الإجراءات'],
    'joined_date' => ['en' => 'joined Date', 'ar' => 'تاريخ الانضمام'],
    'delete' => ['en' => 'Delete', 'ar' => 'حذف'],
    'no_admins' => ['en' => 'No admins found.', 'ar' => 'لا يوجد مسؤولين.'],
    'IsFake' => ['en' => 'Is Fake', 'ar' => 'مزيف أم حقيقي'],

    'total_admins' => ['en' => 'Total Admins', 'ar' => 'إجمالي المسؤولين'],
'current_user' => ['en' => 'Current User', 'ar' => 'المستخدم الحالي'],
'delete' => ['en' => 'Delete', 'ar' => 'حذف'],
'confirm_delete_admin' => ['en' => 'Confirm deleting admin', 'ar' => 'تأكيد حذف المسؤول'],
'action_failed' => ['en' => 'Action failed', 'ar' => 'فشل الإجراء'],
'yes' => ['en' => 'Yes', 'ar' => 'نعم'],
'no' => ['en' => 'No', 'ar' => 'لا'],
'cannot_delete_self' => ['en' => 'You cannot delete your own account.', 'ar' => 'لا يمكنك حذف حسابك الشخصي.'],
'admin_deleted_success' => ['en' => 'Admin deleted successfully.', 'ar' => 'تم حذف المسؤول بنجاح.'],
'no_admins' => ['en' => 'No admins found.', 'ar' => 'لا يوجد مسؤولين.'],

'user_status_updated' => ['en' => 'User status updated successfully.', 'ar' => 'تم تحديث حالة المستخدم بنجاح.'],
'confirm_activate_user' => ['en' => 'Are you sure you want to activate this user?', 'ar' => 'هل أنت متأكد أنك تريد تفعيل هذا المستخدم؟'],
'confirm_deactivate_user' => ['en' => 'Are you sure you want to deactivate this user?', 'ar' => 'هل أنت متأكد أنك تريد تعطيل هذا المستخدم؟'],
// Add to lang.php
'gender_distribution' => [
    'en' => 'Gender Distribution',
    'ar' => 'توزيع الجنس'
],
'total_users' => [
    'en' => 'Total Users',
    'ar' => 'إجمالي المستخدمين'
],
'active_users' => [
    'en' => 'Active Users',
    'ar' => 'المستخدمون النشطون'
],
'inactive_users' => [
    'en' => 'Inactive Users',
    'ar' => 'المستخدمون غير النشطين'
],
'badge_distribution' => ['en' => 'Badge Distribution', 'ar' => 'توزيع الشارات'],
'monthly_signups' => ['en' => 'Monthly Signups', 'ar' => 'عدد المسجلين شهرياً'],
'users' => ['en' => 'users', 'ar' => 'مستخدمين'],


    // Popup messages
    'admin_added_success' => ['en' => 'New admin added successfully.', 'ar' => 'تم ارسال البريد الإلكتروني بنجاح واضافة المسؤول'],
    'admin_deleted_success' => ['en' => 'Admin deleted successfully.', 'ar' => 'تم حذف المسؤول بنجاح.'],
    'cannot_delete_self' => ['en' => 'You cannot delete your own account.', 'ar' => 'لا يمكنك حذف حسابك الشخصي.'],
    'ok' => ['en' => 'OK', 'ar' => 'موافق'],
    'login_required' => [ 'en' => 'Login Required','ar' => 'تسجيل الدخول مطلوب'],
    'please_login_to_like' => ['en' => 'Please login to your account to like reviews!','ar' => 'يرجى تسجيل الدخول لحسابك للإعجاب بالمراجعات!'],
    'please_login_to_report' => ['en' => 'Please login to your account to report a comment!','ar' => 'يرجى تسجيل الدخول إلى حسابك للإبلاغ عن تعليق!'],
    'comment_added_points_updated' => ['en' => 'Comment added and points updated.','ar' => 'تمت إضافة التعليق وتحديث النقاط.'],
    "improve_review_error" => ["en" => "Please improve your review by writing in clear English and providing more details.","ar" => "يرجى تحسين مراجعتك بكتابتها بلغة إنجليزية واضحة وتضمين مزيد من التفاصيل." ],

    // Validation
    'field_required' => ['en' => 'This field is required', 'ar' => 'هذا الحقل مطلوب'],

    // Categories & Brands Section
'categories_title' => [
    'en' => 'Explore Categories',
    'ar' => 'استكشف الفئات',
],

'shop_by_category' => [
    'en' => 'Browse by Category',
    'ar' => 'تصفح حسب الفئة',
],

'no_categories' => [
    'en' => 'No categories available at the moment.',
    'ar' => 'لا توجد فئات متاحة حالياً.',
],

'trusted_brands' => [
    'en' => 'Trusted Brands',
    'ar' => 'العلامات التجارية الموثوقة',
],

'premium_partners' => [
    'en' => 'Premium Partners',
    'ar' => 'شركاء مميزون',
],

'verified' => [
    'en' => 'Verified',
    'ar' => 'موثوق',
],

'no_testimonials' => ['en' => 'No testimonials available at the moment.', 'ar' => 'لا توجد مراجعات حاليًا.'],
'quality' => ['en' => 'Quality', 'ar' => 'الجودة'],

'testimonials_title' => [
    'en' => 'Real User Opinions',
    'ar' => 'آراء المستخدمين الحقيقية',
],

'testimonials_heading' => [
    'en' => 'What People Are Saying About Products',
    'ar' => 'ماذا يقول المستخدمون عن المنتجات؟',
],

'testimonials_subtitle' => [
    'en' => 'Random, honest reviews submitted by real shoppers across the platform. Discover what others think before you buy.',
    'ar' => 'مراجعات عشوائية وصادقة من مستخدمين حقيقيين على المنصة. اكتشف آراء الآخرين قبل أن تتسوق.',
],

    
    'buywise_hero_main' => [
    'en' => 'Real Reviews. Smarter Choices.',
    'ar' => 'مراجعات حقيقية، قرارات أذكى.',
],

'buywise_hero_focus' => [
    'en' => 'Welcome to BuyWise.',
    'ar' => 'مرحبًا بك في BuyWise.',
],

'buywise_hero_desc' => [
    'en' => 'Explore a trusted space where honest reviews, reward systems, and smart comparisons help you shop with confidence.',
    'ar' => 'اكتشف منصة موثوقة تجمع بين المراجعات الصادقة، ونظام المكافآت، والمقارنات الذكية لتتسوق بثقة.',
],

'get_started' => [
    'en' => 'Start Reviewing',
    'ar' => 'ابدأ بالتقييم',
],

'featured_products' => [
    'en' => 'Featured Products',
    'ar' => 'منتجات مميزة'
],

'featured_desc_local' => [
    'en' => 'Discover authentic Jordanian products crafted with pride and trusted by our community. Engage and earn double points!',
    'ar' => 'اكتشف المنتجات الأردنية الأصيلة المصنوعة بفخر، والموثوقة من مجتمعنا. شارك وتفاعل واحصل على ضعف النقاط!'
],


'local_jordanian' => [
    'en' => 'Jordanian Local Picks',
    'ar' => 'مختارات أردنية محلية'
],

'made_in_jordan' => [
    'en' => 'Made in Jordan',
    'ar' => 'صُنع في الأردن'
],

'view_product' => [
    'en' => 'View Product',
    'ar' => 'عرض المنتج'
],

// About BuyWise Section
'about_badge' => [
    'en' => 'About Us',
    'ar' => 'من نحن',
],

'about_buywise_title' => [
    'en' => 'Why Choose BuyWise?',
    'ar' => 'لماذا تختار باي وايز؟',
],

'video_not_supported' => [
    'en' => 'Your browser does not support the video tag.',
    'ar' => 'متصفحك لا يدعم تشغيل الفيديو.',
],

'about_buywise_paragraph' => [
    'en' => 'BuyWise is not just a review platform — it’s a smart ecosystem designed to transform the way people interact with products online. We empower users to share their authentic experiences and help others make informed decisions through trustworthy insights. With advanced AI technology, we detect and filter fake reviews to protect the integrity of our community. Companies on BuyWise earn their credibility by transparency and quality, while users are rewarded for honest contributions. Whether you are a curious shopper or a business seeking loyal customers, BuyWise is your bridge to truth, trust, and meaningful connections.',
        'ar' => 'باي وايز ليست مجرد منصة تقييمات، بل هي منظومة ذكية تهدف إلى تغيير الطريقة التي يتفاعل بها الناس مع المنتجات عبر الإنترنت. نمنح المستخدمين القوة لمشاركة تجاربهم الحقيقية ومساعدة الآخرين على اتخاذ قرارات مدروسة من خلال آراء موثوقة. باستخدام تقنيات الذكاء الاصطناعي المتقدمة، نكشف المراجعات المزيفة ونحمي نزاهة مجتمعنا. الشركات على باي وايز تكتسب مصداقيتها من الشفافية والجودة، بينما يُكافأ المستخدمون على مساهماتهم الصادقة. سواء كنت متسوقًا باحثًا عن الثقة أو شركة تسعى لعملاء أوفياء، فإن باي وايز هو جسر الحقيقة والمصداقية والروابط الأصيلة.',
],




'featured_desc' => [
    'en' => 'Our top selected products, handpicked just for you.',
    'ar' => 'أفضل المنتجات المختارة بعناية من أجلك.',
],

'featured_products' => [
    'en' => 'Featured Products',
    'ar' => 'المنتجات المميزة',
],


'random_products' => [
    'en' => 'Surprise Picks',
    'ar' => 'اختيارات عشوائية',
],

'random_desc' => [
    'en' => 'Explore something new with our randomly selected products.',
    'ar' => 'اكتشف شيئاً جديداً من خلال منتجات مختارة عشوائياً.',
],


'browse_categories' => [
    'en' => 'Explore Products',
    'ar' => 'استعرض المنتجات',
],

    // Page title & breadcrumbs
    'manage_categories' => ['en' => 'Manage Categories', 'ar' => 'إدارة الفئات'],

    // Form labels & buttons
    'add_new_category' => ['en' => 'Add New Category', 'ar' => 'إضافة فئة جديدة'],
    'category_name' => ['en' => 'Category Name', 'ar' => 'اسم الفئة'],
    'select_category_status' => ['en' => 'Select Category Status', 'ar' => 'اختر حالة الفئة'],
    'active' => ['en' => 'Active', 'ar' => 'نشط'],
    'inactive' => ['en' => 'Inactive', 'ar' => 'غير نشط'],
    'add_category' => ['en' => 'Add Category', 'ar' => 'إضافة فئة'],
    'existing_categories' => ['en' => 'Existing Categories', 'ar' => 'التصنيفات الحالية'],
    'name' => ['en' => 'Name', 'ar' => 'الاسم'],
    'status' => ['en' => 'Status', 'ar' => 'الحالة'],
    'edit' => ['en' => 'Edit', 'ar' => 'تعديل'],
    'cancel' => ['en' => 'Cancel', 'ar' => 'إلغاء'],
    'save_changes' => ['en' => 'Save Changes', 'ar' => 'حفظ التعديلات'],

    // Table
    'no_categories' => ['en' => 'No categories found.', 'ar' => 'لا توجد فئات.'],
    'view' => ['en' => 'View', 'ar' => 'عرض'],
    'product_details' => ['en' => 'Product Details', 'ar' => 'تفاصيل المنتج'],
    'pending_approval' => ['en' => 'Pending Approval', 'ar' => 'بانتظار الموافقة'],

    'pending_products' => ['en' => 'Pending Products', 'ar' => 'المنتجات قيد الانتظار'],
'approved_products' => ['en' => 'Approved Products', 'ar' => 'المنتجات المعتمدة'],
'approved_company_products' => ['en' => 'Company Products', 'ar' => 'منتجات الشركات'],
'user_name' => ['en' => 'User Name', 'ar' => 'اسم المستخدم'],
'company_name' => ['en' => 'Company Name', 'ar' => 'اسم الشركة'],
'jod' => ['en' => 'JOD', 'ar' => 'د.أ'],

'total_comments' => ['en' => 'Total Comments', 'ar' => 'إجمالي التعليقات'],
'active_comments' => ['en' => 'Active Comments', 'ar' => 'التعليقات النشطة'],
'reported_comments' => ['en' => 'Reported Comments', 'ar' => 'التعليقات المبلغ عنها'],
'deactivated_products' => [
    'en' => 'Deactivated Products',
    'ar' => 'المنتجات المعلقة'
],

'fake_reviews_by_user' => ['en' => 'Fake Reviews by User', 'ar' => 'المراجعات المزيفة للمستخدم'],
'user_not_found' => ['en' => 'User not found.', 'ar' => 'المستخدم غير موجود.'],
'invalid_user_id' => ['en' => 'Invalid or missing User ID.', 'ar' => 'معرّف المستخدم غير صالح أو مفقود.'],
'review_content' => ['en' => 'Review Content', 'ar' => 'محتوى المراجعة'],
'date' => ['en' => 'Date', 'ar' => 'التاريخ'],
'product' => ['en' => 'Product', 'ar' => 'المنتج'],
'username' => ['en' => 'Username', 'ar' => 'اسم المستخدم'],
'no_fake_reviews_found' => ['en' => 'No fake reviews found for this user.', 'ar' => 'لم يتم العثور على مراجعات مزيفة لهذا المستخدم.'],
'back_to_dashboard' => ['en' => 'Back to Dashboard', 'ar' => 'العودة إلى لوحة التحكم'],

'total_reported_users' => [
    'en' => 'Total Reported Users',
    'ar' => 'إجمالي المستخدمين المُبلغ عنهم'
],
'ready_for_deletion' => [
    'en' => 'Ready for Deletion',
    'ar' => 'جاهز للحذف'
],
'ready_for_ban' => [
    'en' => 'Ready for Ban',
    'ar' => 'جاهز للحظر'
],
'avg_fake_reviews' => [
    'en' => 'Avg. Fake Reviews',
    'ar' => 'متوسط المراجعات المزيفة'
],

    // Dashboard Sections
    'dashboard' => ['en' => 'Dashboard', 'ar' => 'لوحة التحكم'],
    'welcome' => ['en' => 'Welcome', 'ar' => 'مرحبًا'],
    'dashboard_intro' => ['en' => 'Here is an overview of your platform.', 'ar' => 'إليك نظرة عامة على منصتك.'],
    'last_login' => ['en' => 'Last login', 'ar' => 'آخر تسجيل دخول'],

    // Stats
    'quick_overview' => ['en' => 'Quick Overview', 'ar' => 'نظرة سريعة'],
    'total_users' => ['en' => 'Total Users', 'ar' => 'إجمالي المستخدمين'],
    'total_products' => ['en' => 'Total Products', 'ar' => 'إجمالي المنتجات'],
    'total_comments' => ['en' => 'Total Comments', 'ar' => 'إجمالي التعليقات'],
    'reported_users' => ['en' => 'Reported Users', 'ar' => 'المستخدمون المُبلغ عنهم'],

    // Menu Titles
    'management_tools' => ['en' => 'Management Tools', 'ar' => 'أدوات الإدارة'],
    'admin_settings' => ['en' => 'Admin Settings', 'ar' => 'إعدادات المشرف'],
    'manage_your_admin_account' => ['en' => 'Manage your admin account', 'ar' => 'إدارة حساب المشرف الخاص بك'],
    'admin_admins' => ['en' => 'Admin Accounts', 'ar' => 'حسابات المشرفين'],
    'manage_admin_accounts' => ['en' => 'Manage all admin accounts', 'ar' => 'إدارة جميع حسابات المشرفين'],
    'admin_users' => ['en' => 'Users', 'ar' => 'المستخدمون'],
    'manage_user_accounts' => ['en' => 'Manage user accounts', 'ar' => 'إدارة حسابات المستخدمين'],
    'admin_pending_user_products' => ['en' => 'Pending Products', 'ar' => 'المنتجات المعلقة'],
    'review_pending_products' => ['en' => 'Review pending products', 'ar' => 'مراجعة المنتجات المعلقة'],
    'admin_products' => ['en' => 'Products', 'ar' => 'المنتجات'],
    'manage_all_products' => ['en' => 'Manage all products', 'ar' => 'إدارة جميع المنتجات'],
    'admin_comments_reports' => ['en' => 'Comments & Reports', 'ar' => 'التعليقات والتقارير'],
    'manage_user_comments' => ['en' => 'Manage user comments', 'ar' => 'إدارة تعليقات المستخدمين'],
    'admin_fake_content' => ['en' => 'Fake Content Reports', 'ar' => 'تقارير المحتوى المزيف'],
    'review_reported_content' => ['en' => 'Review reported content', 'ar' => 'مراجعة المحتوى المُبلغ عنه'],
    'admin_companies' => ['en' => 'Companies', 'ar' => 'الشركات'],
    'manage_companies' => ['en' => 'Manage company accounts', 'ar' => 'إدارة حسابات الشركات'],
    'admin_categories' => ['en' => 'Categories', 'ar' => 'الفئات'],
    'manage_categories' => ['en' => 'Manage categories', 'ar' => 'إدارة الفئات'],
    'admin_company_products' => ['en' => 'Company Products', 'ar' => 'منتجات الشركات'],
    'manage_company_products' => ['en' => 'Manage company products', 'ar' => 'إدارة منتجات الشركات'],

    // Notifications
    'pending_products_notification' => ['en' => 'products pending approval', 'ar' => 'منتج قيد الانتظار للموافقة'],
    'reports_need_attention' => ['en' => 'reports need attention', 'ar' => 'تقارير بحاجة لمراجعة'],
    'all_rights_reserved' => ['en' => 'All rights reserved.', 'ar' => 'جميع الحقوق محفوظة.'],

'reported_users_management' => ['en' => 'Reported Users Management', 'ar' => 'إدارة المستخدمين المُبلغ عنهم'],


    // Status toggling
    'activate' => ['en' => 'Activate', 'ar' => 'تفعيل'],
    'deactivate' => ['en' => 'Deactivate', 'ar' => 'تعطيل'],
    'status_updated' => ['en' => 'Status updated successfully.', 'ar' => 'تم تحديث الحالة بنجاح.'],

    // Popup messages
    'please_fill_all_fields' => ['en' => 'Please fill in all fields.', 'ar' => 'يرجى تعبئة جميع الحقول.'],
    'please_select_image' => ['en' => 'Please select an image.', 'ar' => 'يرجى اختيار صورة.'],
    'category_added_successfully' => ['en' => 'Category added successfully.', 'ar' => 'تمت إضافة الفئة بنجاح.'],
    'category_exists' => ['en' => 'Category already exists.', 'ar' => 'الفئة موجودة مسبقاً.'],
    'failed_to_add_category' => ['en' => 'Failed to add category.', 'ar' => 'فشل في إضافة الفئة.'],
    'category_updated' => ['en' => 'Category updated successfully.', 'ar' => 'تم تحديث الفئة بنجاح.'],
    'confirm_delete_category' => ['en' => 'Are you sure you want to delete this category?', 'ar' => 'هل أنت متأكد من حذف هذه الفئة؟'],
    'category_deleted' => ['en' => 'Category deleted successfully.', 'ar' => 'تم حذف الفئة بنجاح.'],
    'delete_failed' => ['en' => 'Failed to delete category.', 'ar' => 'فشل في حذف الفئة.'],
    'edit_category' => ['en' => 'Edit Category', 'ar' => 'تعديل الفئة'],

    // General
    'view' => ['en' => 'View', 'ar' => 'عرض'],
    'guest' => ['en' => 'Guest', 'ar' => 'زائر'],

    // Admin and Page Structure
    'manage_comments' => ['en' => 'Manage Comments', 'ar' => 'إدارة التعليقات'],
    'admin_pending_user_products' => ['en' => 'Pending User Products', 'ar' => 'منتجات المستخدمين المعلقة'],


    // Filter Section
    'filter_comments' => ['en' => 'Filter Comments', 'ar' => 'تصفية التعليقات'],
    'category' => ['en' => 'Category', 'ar' => 'الفئة'],
    'all_categories' => ['en' => 'All Categories', 'ar' => 'جميع الفئات'],
    'product' => ['en' => 'Product', 'ar' => 'المنتج'],
    'all_products' => ['en' => 'All Products', 'ar' => 'جميع المنتجات'],
    'apply' => ['en' => 'Apply', 'ar' => 'تطبيق'],
    'try_different_search' => ['en' => 'Try a different search or keyword.','ar' => 'جرّب بحثًا أو كلمة مفتاحية مختلفة.'],
    'sponsored' => ['en' => 'Sponsored','ar' => 'مُموّل'],


    // Comments Table
    'all_comments' => ['en' => 'All Comments', 'ar' => 'جميع التعليقات'],
    'comment' => ['en' => 'Comment', 'ar' => 'التعليق'],
    'user' => ['en' => 'User', 'ar' => 'المستخدم'],

    // Reported Comments Section
    'reported_comments' => ['en' => 'Reported Comments', 'ar' => 'التعليقات المُبلّغ عنها'],
    'delete_comment' => ['en' => 'Delete Comment', 'ar' => 'حذف التعليق'],
    'cancel_report' => ['en' => 'Cancel Report', 'ar' => 'إلغاء البلاغ'],
    'reported_by' => ['en' => 'Reported By', 'ar' => 'أُبلِغ عنه بواسطة'],
    'report_date' => ['en' => 'Report Date', 'ar' => 'تاريخ البلاغ'],
    'full_comment' => ['en' => 'Full Comment', 'ar' => 'نص التعليق الكامل'],


    // Popup Messages
    'comment_updated' => ['en' => 'Comment status updated.', 'ar' => 'تم تحديث حالة التعليق.'],
    'comment_deleted' => ['en' => 'Comment deleted successfully.', 'ar' => 'تم حذف التعليق بنجاح.'],
    'report_cancelled' => ['en' => 'Report cancelled.', 'ar' => 'تم إلغاء البلاغ.'],
    'cancel_failed' => ['en' => 'Failed to cancel report.', 'ar' => 'فشل في إلغاء البلاغ.'],
    'confirm_delete_comment' => ['en' => 'Are you sure you want to delete this comment?', 'ar' => 'هل أنت متأكد من حذف هذا التعليق؟'],
    'no_comments_found' => ['en' => 'No comments found.', 'ar' => 'لا توجد تعليقات.'],
    'no_reported_comments' => ['en' => 'No reported comments found.', 'ar' => 'لا توجد تعليقات مُبلّغ عنها.'],
    'delete_comment_title' => ['en' => 'Are you sure you want to delete this comment?','ar' => 'هل أنت متأكد أنك تريد حذف هذا التعليق؟'],
    'delete_comment_message' => ['en' => 'This action cannot be undone. Are you sure?','ar' => 'هذا الإجراء لا يمكن التراجع عنه. هل أنت متأكد؟'],
    
    // Page title and breadcrumb
    'approve_companies' => ['en' => 'Approve Companies', 'ar' => 'الموافقة على الشركات'],
    'pending_companies' => ['en' => 'Pending Companies', 'ar' => 'الشركات قيد الانتظار'],

    // Buttons
    'approve' => ['en' => 'Approve', 'ar' => 'موافقة'],
    'reject' => ['en' => 'Reject', 'ar' => 'رفض'],

    // Messages
    'company_approved' => ['en' => 'Company approved successfully.', 'ar' => 'تمت الموافقة على الشركة بنجاح.'],
    'company_rejected' => ['en' => 'Company request has been rejected.', 'ar' => 'تم رفض طلب الشركة.'],
    'confirm_reject' => ['en' => 'Are you sure you want to reject this company?', 'ar' => 'هل أنت متأكد من رفض هذه الشركة؟'],
    'no_pending_companies' => ['en' => 'No pending company requests found.', 'ar' => 'لا توجد شركات قيد الانتظار.'],

    // Page title and breadcrumbs
    'manage_products' => ['en' => 'Manage Products', 'ar' => 'إدارة المنتجات'],
    'filter_by_category' => ['en' => 'Filter by Category', 'ar' => 'تصفية حسب الفئة'],
    'select_category' => ['en' => 'Select Category', 'ar' => 'اختر فئة'],

    // Products Table
    'products' => ['en' => 'Products', 'ar' => 'المنتجات'],
    'image' => ['en' => 'Image', 'ar' => 'الصورة'],
    'description' => ['en' => 'Description', 'ar' => 'الوصف'],
    'added_by' => ['en' => 'Added By', 'ar' => 'أُضيف بواسطة'],
    'unknown' => ['en' => 'Unknown', 'ar' => 'غير معروف'],

    // Alerts and Popups
    'please_select_category' => ['en' => 'Please select a category first.', 'ar' => 'يرجى اختيار فئة أولاً.'],
    'no_products_found' => ['en' => 'No products found in this category.', 'ar' => 'لا توجد منتجات في هذه الفئة.'],
    'confirm_delete_product' => ['en' => 'Are you sure you want to delete this product?', 'ar' => 'هل أنت متأكد أنك تريد حذف هذا المنتج؟'],
    'product_deleted' => ['en' => 'Product deleted successfully.', 'ar' => 'تم حذف المنتج بنجاح.'],

    // Page title and breadcrumbs
    'manage_users' => ['en' => 'Manage Users', 'ar' => 'إدارة المستخدمين'],
    'all_users' => ['en' => 'All Users', 'ar' => 'جميع المستخدمين'],
    'search_by_email' => ['en' => 'Search by Email', 'ar' => 'البحث بالبريد الإلكتروني'],
    'search' => ['en' => 'Search', 'ar' => 'بحث'],
    'reset' => ['en' => 'Reset', 'ar' => 'إعادة تعيين'],

    // Table columns
    'phone' => ['en' => 'Phone', 'ar' => 'رقم الهاتف'],
    'address' => ['en' => 'Address', 'ar' => 'العنوان'],
    'birth' => ['en' => 'Birth Date', 'ar' => 'تاريخ الميلاد'],
    'gender' => ['en' => 'Gender', 'ar' => 'الجنس'],

    // Gender
    'male' => ['en' => 'Male', 'ar' => 'ذكر'],
    'female' => ['en' => 'Female', 'ar' => 'أنثى'],

    // Popups and feedback
    'confirm_delete_user' => ['en' => 'Are you sure you want to delete this user?', 'ar' => 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟'],
    'user_status_updated' => ['en' => 'User status updated.', 'ar' => 'تم تحديث حالة المستخدم.'],
    'user_deleted' => ['en' => 'User deleted successfully.', 'ar' => 'تم حذف المستخدم بنجاح.'],
    'no_users_available' => ['en' => 'No users available.', 'ar' => 'لا يوجد مستخدمون متاحون.'],
    'sort_rating_high' => ['en' => 'Rating (High to Low)', 'ar' => 'التقييم (من الأعلى إلى الأقل)'],
    'sort_rating_low' => ['en' => 'Rating (Low to High)', 'ar' => 'التقييم (من الأقل إلى الأعلى)'],


    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Titles
    'add_products_title' => ['en' => 'Add Products', 'ar' => 'إضافة منتجات'],
    'search_products' => ['en' => 'Search products...', 'ar' => 'ابحث عن المنتجات...'],
    'sort_newest' => ['en' => 'Newest', 'ar' => 'الأحدث'],
    'sort_oldest' => ['en' => 'Oldest', 'ar' => 'الأقدم'],
    'sort_az' => ['en' => 'A–Z', 'ar' => 'من أ إلى ي'],
    'sort_za' => ['en' => 'Z–A', 'ar' => 'من ي إلى أ'],
    'filter_all_sources' => ['en' => 'All Sources', 'ar' => 'جميع المصادر'],
    'filter_company' => ['en' => 'Company Products', 'ar' => 'منتجات الشركات'],
    'filter_user' => ['en' => 'User Products', 'ar' => 'منتجات المستخدمين'],
    'filter' => ['en' => 'Filter', 'ar' => 'تصفية'],
    'trending_title' => ['en' => 'Trending Products', 'ar' => 'المنتجات الرائجة'],
    'view_product' => ['en' => 'View Product', 'ar' => 'عرض المنتج'],
    'no_trending_products' => ['en' => 'No trending products available right now.', 'ar' => 'لا توجد منتجات رائجة حالياً.'],
    'by' => ['en' => 'by', 'ar' => 'بواسطة'],

    'product_name' => ['en' => 'Product Name', 'ar' => 'اسم المنتج'],
    'product_description' => ['en' => 'Product Description', 'ar' => 'وصف المنتج'],
    'product_category' => ['en' => 'Product Category', 'ar' => 'فئة المنتج'],
    'product_rating' => ['en' => 'Product Rating', 'ar' => 'تقييم المنتج'],
    'main_image' => ['en' => 'Main Product Image', 'ar' => 'الصورة الرئيسية للمنتج'],
    'additional_images' => ['en' => 'Additional Images (Up to 2)', 'ar' => 'صور إضافية (بحد أقصى 2)'],
    'product_status' => ['en' => 'Product Status', 'ar' => 'حالة المنتج'],

    // Dropdowns
    'select_status' => ['en' => 'Select Status', 'ar' => 'اختر الحالة'],

    // Buttons
    'add_product_btn' => ['en' => 'Add Product', 'ar' => 'إضافة المنتج'],

'my_vouchers' => ['en' => 'My Vouchers', 'ar' => 'قسائمي'],
'no_vouchers' => ['en' => 'No vouchers found.', 'ar' => 'لا توجد قسائم.'],
'discount' => ['en' => 'Discount', 'ar' => 'الخصم'],
'min_points' => ['en' => 'Min Points', 'ar' => 'الحد الأدنى من النقاط'],
'expiry_date' => ['en' => 'Expiry Date', 'ar' => 'تاريخ الانتهاء'],
'company' => ['en' => 'Company', 'ar' => 'الشركة'],
'assigned_at' => ['en' => 'Assigned At', 'ar' => 'تاريخ الإسناد'],
'active' => ['en' => 'Active', 'ar' => 'نشط'],
'expired' => ['en' => 'Expired', 'ar' => 'منتهي'],
'redeemed' => ['en' => 'Redeemed', 'ar' => 'مستخدم'],

'country' => ['en' => 'Country', 'ar' => 'الدولة'],
'select_country' => ['en' => 'Select a country', 'ar' => 'اختر الدولة'],


'pending_company_accounts' => [
    'en' => 'Pending Company Accounts',
    'ar' => 'حسابات الشركات قيد المراجعة'
],

'company_approved' => [
    'en' => 'Company approved successfully.',
    'ar' => 'تمت الموافقة على الشركة بنجاح.'
],

'company_rejected' => [
    'en' => 'Company rejected and removed.',
    'ar' => 'تم رفض الشركة وحذفها.'
],

'confirm_reject_company' => [
    'en' => 'Are you sure you want to reject this company?',
    'ar' => 'هل أنت متأكد أنك تريد رفض هذه الشركة؟'
],

'no_pending_companies' => [
    'en' => 'No pending companies at the moment.',
    'ar' => 'لا توجد شركات قيد الانتظار حالياً.'
],

'company_name' => [
    'en' => 'Company Name',
    'ar' => 'اسم الشركة'
],

'company_email' => [
    'en' => 'Company Email',
    'ar' => 'البريد الإلكتروني للشركة'
],

'country' => [
    'en' => 'Country',
    'ar' => 'الدولة'
],

'approved_companies' => ['en' => 'Approved Companies', 'ar' => 'الشركات المعتمدة'],
'no_approved_companies' => ['en' => 'No approved companies found.', 'ar' => 'لا توجد شركات معتمدة.'],

// lang.php additions
'pending_company_accounts' => [
    'en' => 'Pending Company Accounts',
    'ar' => 'حسابات الشركات المعلقة'
],
'approved_companies' => [
    'en' => 'Approved Companies',
    'ar' => 'الشركات المعتمدة'
],
'company_name' => [
    'en' => 'Company Name',
    'ar' => 'اسم الشركة'
],
'company_email' => [
    'en' => 'Company Email',
    'ar' => 'بريد الشركة الإلكتروني'
],
'country' => [
    'en' => 'Country',
    'ar' => 'الدولة'
],
'actions' => [
    'en' => 'Actions',
    'ar' => 'الإجراءات'
],
'approve' => [
    'en' => 'Approve',
    'ar' => 'موافقة'
],
'reject' => [
    'en' => 'Reject',
    'ar' => 'رفض'
],
'toggle' => [
    'en' => 'Toggle',
    'ar' => 'تبديل'
],
'delete' => [
    'en' => 'Delete',
    'ar' => 'حذف'
],
'no_pending_companies' => [
    'en' => 'No pending companies found.',
    'ar' => 'لا توجد شركات معلقة.'
],
'no_approved_companies' => [
    'en' => 'No approved companies found.',
    'ar' => 'لا توجد شركات معتمدة.'
],
'company_approved' => [
    'en' => 'Company approved successfully.',
    'ar' => 'تمت الموافقة على الشركة بنجاح.'
],
'company_rejected' => [
    'en' => 'Company rejected and deleted.',
    'ar' => 'تم رفض الشركة وحذفها.'
],
'company_deleted' => [
    'en' => 'Company deleted.',
    'ar' => 'تم حذف الشركة.'
],
'company_status_updated' => [
    'en' => 'Company status updated.',
    'ar' => 'تم تحديث حالة الشركة.'
],
'confirm_reject_company' => [
    'en' => 'Are you sure you want to reject this company?',
    'ar' => 'هل أنت متأكد أنك تريد رفض هذه الشركة؟'
],
'confirm_delete_company' => [
    'en' => 'Are you sure you want to delete this company?',
    'ar' => 'هل أنت متأكد أنك تريد حذف هذه الشركة؟'
],


'approve' => [
    'en' => 'Approve',
    'ar' => 'موافقة'
],

'reject' => [
    'en' => 'Reject',
    'ar' => 'رفض'
],

'admin_company_products' => [
    'en' => "Manage Company's Products",
    'ar' => 'إدارة منتجات الشركات'
],



    // JavaScript Feedback
    'must_not_contain_numbers' => ['en' => 'Product name must not contain numbers.', 'ar' => 'يجب ألا يحتوي اسم المنتج على أرقام.'],
    'main_image_required' => ['en' => 'Main product image is required.', 'ar' => 'الصورة الرئيسية للمنتج مطلوبة.'],
    'product_exists' => ['en' => 'Product already exists.', 'ar' => 'المنتج موجود بالفعل.'],
    'product_added' => ['en' => 'Product added successfully!', 'ar' => 'تمت إضافة المنتج بنجاح!'],
    'invalid_image_type' => ['en' => 'Invalid image type. Please use JPEG, PNG, GIF or WEBP.', 'ar' => 'نوع الصورة غير صالح. الرجاء استخدام JPEG أو PNG أو GIF أو WEBP.'],
    'image_too_large' => ['en' => 'Image file is too large. Maximum size is 2MB.', 'ar' => 'حجم الصورة كبير جداً. الحد الأقصى هو 2 ميجابايت.'],
    'upload_failed' => ['en' => 'Upload failed.', 'ar' => 'فشل التحميل.'],

    // Image Preview
    'only_first_images' => [
        'en' => 'Only the first {count} images will be uploaded. You selected {selected}.',
        'ar' => 'سيتم تحميل أول {count} صور فقط. لقد قمت بتحديد {selected}.'
    ],
    'preview_alt' => ['en' => 'Preview', 'ar' => 'معاينة'],

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
'about_buywise_title' => ['en' => 'About BuyWise', 'ar' => 'حول BuyWise'],
'about_buywise_description1' => [
    'en' => 'BuyWise is an AI-powered product review platform that helps users make smarter choices by ensuring reviews are authentic and trustworthy.',
    'ar' => 'BuyWise هو منصة مراجعات منتجات مدعومة بالذكاء الاصطناعي تساعد المستخدمين على اتخاذ قرارات شراء أذكى من خلال ضمان المصداقية.'
],
'about_buywise_point1' => ['en' => 'Detects and flags fake reviews using AI.', 'ar' => 'يكتشف المراجعات المزيفة ويبلغ عنها باستخدام الذكاء الاصطناعي.'],
'about_buywise_point2' => ['en' => 'Earn points, badges, and vouchers for authentic content.', 'ar' => 'اكسب نقاطًا وشارات وقسائم مقابل المحتوى الأصيل.'],
'about_buywise_point3' => ['en' => 'Companies can promote their products transparently.', 'ar' => 'يمكن للشركات الترويج لمنتجاتها بشفافية.'],
'about_buywise_point4' => ['en' => 'Fully bilingual in English and Arabic.', 'ar' => 'يدعم الإنجليزية والعربية بالكامل.'],
'about_buywise_point5' => ['en' => 'Interactive and moderated review system.', 'ar' => 'نظام مراجعة تفاعلي ومراقب.'],



    // Footer Sections
    'get_in_touch' => ['en' => 'Get In Touch', 'ar' => 'تواصل معنا'],
    'addresss' => ['en' => 'Amman, Jordan', 'ar' => 'عمَان - المملكة الأردنية الهاشمية'],
    'phonee' => ['en' => '+962795562276', 'ar' => '+962795562276'],
    'emaill' => ['en' => 'buywise2025@gmail.com', 'ar' => 'buywise2025@gmail.com'],
    'follow_us' => ['en' => 'Follow Us', 'ar' => 'تابعنا'],

    // Newsletter
    'newsletter' => ['en' => 'Newsletter', 'ar' => 'النشرة البريدية'],
    'newsletter_text' => ['en' => 'Subscribe to our newsletter to stay updated.', 'ar' => 'اشترك في النشرة البريدية لدينا للبقاء على اطلاع.'],
    'your_email' => ['en' => 'Your Email', 'ar' => 'بريدك الإلكتروني'],
    'join_us' => ['en' => 'Join Us', 'ar' => 'انضم إلينا'],

    // Useful Links
    'useful_links' => ['en' => 'Useful Links', 'ar' => 'روابط مفيدة'],
    'home' => ['en' => 'Home', 'ar' => 'الرئيسية'],
    'about_us' => ['en' => 'About Us', 'ar' => 'من نحن'],
    'our_goals' => ['en' => 'Our Goals', 'ar' => 'أهدافنا'],
    'categories' => ['en' => 'Categories', 'ar' => 'الفئات'],
    'location' => ['en' => 'Location', 'ar' => 'الموقع'],
    'sign_in' => ['en' => 'Sign In', 'ar' => 'تسجيل الدخول'],

    // Location
    'our_location' => ['en' => 'Our Location', 'ar' => 'موقعنا'],

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Forgot Password Page
    'forgot_password_title' => ['en' => 'Forgot Password', 'ar' => 'نسيت كلمة المرور'],
    'forgot_password' => ['en' => 'Forgot Your Password?', 'ar' => 'هل نسيت كلمة المرور؟'],
    'forgot_password_instruction' => [
        'en' => 'Enter your email address below and we will send you a link to reset your password.',
        'ar' => 'أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.'
    ],
    'send_reset_link' => ['en' => 'Send Reset Link', 'ar' => 'إرسال رابط إعادة التعيين'],
    'remember_your_password' => ['en' => 'Remember your password?', 'ar' => 'هل تتذكر كلمة المرور؟'],
    'login' => ['en' => 'Login', 'ar' => 'تسجيل الدخول'],

    // Email Content
    'hello_friend' => ['en' => 'Hello, friend', 'ar' => 'مرحباً صديقي'],
    'reset_password' => ['en' => 'Reset Password', 'ar' => 'إعادة تعيين كلمة المرور'],
    'email_sent_to' => ['en' => 'Email sent to', 'ar' => 'تم الإرسال إلى'],

    // Result Messages
    'reset_email_sent' => [
        'en' => 'Reset link has been sent to your email.',
        'ar' => 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.'
    ],
    'error_reset_request' => [
        'en' => 'There was an error processing your request.',
        'ar' => 'حدث خطأ أثناء معالجة طلبك.'
    ],
    'error_email_not_found' => [
        'en' => 'No user found with that email address.',
        'ar' => 'لم يتم العثور على مستخدم بهذا البريد الإلكتروني.'
    ],

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Login & Auth
    'login_title' => ['en' => 'Login', 'ar' => 'تسجيل الدخول'],
    'login_account' => ['en' => 'Log in to your account', 'ar' => 'تسجيل الدخول إلى حسابك'],
    'register_as_company' => ['en' => 'Register as Company', 'ar' => 'تسجيل كشركة'],
    'register' => ['en' => 'Register','ar' => 'تسجيل'],


    // Registration
    'create_account' => ['en' => 'Create Account', 'ar' => 'إنشاء حساب'],
    'username' => ['en' => 'Username', 'ar' => 'اسم المستخدم'],
    'sign_up' => ['en' => 'Sign Up', 'ar' => 'إنشاء حساب'],

    // Overlay Panel
    'enter_details_msg' => ['en' => 'Enter your personal details to create an account', 'ar' => 'أدخل بياناتك الشخصية لإنشاء حساب'],
    'welcome_back' => ['en' => 'Welcome Back!', 'ar' => 'مرحباً بعودتك!'],
    'keep_connected_msg' => ['en' => 'To keep connected with us, please login with your info', 'ar' => 'للبقاء على اتصال معنا، يرجى تسجيل الدخول بمعلوماتك'],

    // Validation & Errors
    'password_requirements' => [
        'en' => 'Password must be at least 8 characters and include uppercase, lowercase, number, and special character.',
        'ar' => 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتحتوي على حرف كبير وصغير ورقم ورمز خاص.'
    ],
    'error_required_fields' => ['en' => 'Please fill in all required fields.', 'ar' => 'يرجى تعبئة جميع الحقول المطلوبة.'],
    'error_incorrect_email' => ['en' => 'Invalid email format.', 'ar' => 'تنسيق البريد الإلكتروني غير صحيح.'],
    'error_invalid_credentials' => ['en' => 'Invalid email or password.', 'ar' => 'البريد الإلكتروني أو كلمة المرور غير صحيحة.'],
    'error_security_token' => ['en' => 'Security token mismatch. Please refresh and try again.', 'ar' => 'رمز الأمان غير صالح. يرجى التحديث والمحاولة مرة أخرى.'],
    'error_server_connection' => ['en' => 'Could not connect to the server. Please try again later.', 'ar' => 'تعذر الاتصال بالخادم. الرجاء المحاولة لاحقاً.'],
    'error_field_required' => ['en' => 'This field is required.', 'ar' => 'هذا الحقل مطلوب.'],
    'error_name_no_numbers' => ['en' => 'Name must not contain numbers.', 'ar' => 'لا يجب أن يحتوي الاسم على أرقام.'],
    'error_invalid_email' => ['en' => 'Please enter a valid email.', 'ar' => 'يرجى إدخال بريد إلكتروني صالح.'],
    'error_password_length' => ['en' => 'Password must be at least 8 characters.', 'ar' => 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.'],
    'error_password_uppercase' => ['en' => 'Password must include at least one uppercase letter.', 'ar' => 'يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل.'],
    'error_password_lowercase' => ['en' => 'Password must include at least one lowercase letter.', 'ar' => 'يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل.'],
    'error_password_number' => ['en' => 'Password must include at least one number.', 'ar' => 'يجب أن تحتوي كلمة المرور على رقم واحد على الأقل.'],
    'error_password_special' => ['en' => 'Password must include at least one special character.', 'ar' => 'يجب أن تحتوي كلمة المرور على رمز خاص واحد على الأقل.'],
    'error_passwords_mismatch' => ['en' => 'Passwords do not match.', 'ar' => 'كلمتا المرور غير متطابقتين.'],
    'error_phone_format' => ['en' => 'Phone number must start with 07 and be 10 digits.', 'ar' => 'يجب أن يبدأ رقم الهاتف بـ 07 ويتكون من 10 أرقام.'],
    'error_email_exists' => ['en' => 'This email is already registered.', 'ar' => 'هذا البريد الإلكتروني مسجل بالفعل.'],
    'error_email_sending' => ['en' => 'Failed to send verification email.', 'ar' => 'فشل في إرسال بريد التحقق.'],
    'error_registration_failed' => ['en' => 'Registration failed. Please try again.', 'ar' => 'فشل التسجيل. الرجاء المحاولة مرة أخرى.'],
    'account_verified_success' => ['en' => 'Your account has been successfully verified!', 'ar' => 'تم التحقق من حسابك بنجاح!'],
    'company_login_title' => ['en' => 'Company Login', 'ar' => 'تسجيل دخول الشركة'],
    'company_login' => ['en' => 'Login to Your Company Account', 'ar' => 'تسجيل الدخول إلى حساب شركتك'],
    'register_company' => ['en' => 'Register Your Company', 'ar' => 'تسجيل شركتك'],
    'company_name' => ['en' => 'Company Name', 'ar' => 'اسم الشركة'],
    'company_email' => ['en' => 'Company Email', 'ar' => 'البريد الإلكتروني للشركة'],
    'Login_as_user' => ['en' => 'Login as User', 'ar' => 'تسجيل الدخول كمستخدم'],
    'register_as_user' => ['en' => 'Register as User', 'ar' => 'التسجيل كمستخدم'],
    'hello_company' => ['en' => 'Hello, Company!', 'ar' => 'مرحباً بالشركة!'],
    'welcome_back_company' => ['en' => 'Welcome Back!', 'ar' => 'مرحباً بعودتك!'],
    'enter_company_details_msg' => ['en' => 'Enter your company details to start your journey with us', 'ar' => 'أدخل تفاصيل شركتك للبدء معنا'],
    'keep_connected_company_msg' => ['en' => 'Keep connected with your company account', 'ar' => 'ابق متصلاً بحساب شركتك'],
    'company_email_not_verified' => ['en' => 'Your company email has not been verified.', 'ar' => 'لم يتم التحقق من البريد الإلكتروني للشركة.'],
    'company_pending_approval' => ['en' => 'Your company account is pending admin approval.', 'ar' => 'حساب شركتك بانتظار موافقة المسؤول.'],
    'company_not_found' => ['en' => 'Company not found.', 'ar' => 'الشركة غير موجودة.'],
    'Login_as_company' => ['en' => 'Login as Company', 'ar' => 'تسجيل الدخول كشركة'],
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Page Metadata
    'title' => ['en' => 'Your Profile', 'ar' => 'ملفك الشخصي'],
    'meta_keywords' => ['en' => 'user, profile, products, comments, BuyWise', 'ar' => 'مستخدم، ملف شخصي، منتجات، تعليقات، باي وايز'],
    'meta_description' => ['en' => 'Manage your profile, products, and comments.', 'ar' => 'إدارة ملفك الشخصي، المنتجات، والتعليقات.'],

    // Sections
    'comments' => ['en' => 'Comments', 'ar' => 'التعليقات'],

    // Tabs
    'tab_products' => ['en' => 'Products', 'ar' => 'المنتجات'],
    'tab_comments' => ['en' => 'Comments', 'ar' => 'التعليقات'],
    'tab_settings' => ['en' => 'Account Settings', 'ar' => 'إعدادات الحساب'],

    'category_name_en' => ['en' => 'Category Name (EN)', 'ar' => 'اسم الفئة (إنجليزي)'],
'category_name_ar' => ['en' => 'Category Name (AR)', 'ar' => 'اسم الفئة (عربي)'],

'verify_account_title' => [
    'en' => 'Verify Your Company Account',
    'ar' => 'تحقق من حساب شركتك'
],

'verify_account_description' => [
    'en' => 'Enter the 6-digit verification code sent to your email address.',
    'ar' => 'أدخل رمز التحقق المكوّن من 6 أرقام الذي تم إرساله إلى بريدك الإلكتروني.'
],

'enter_verification_code' => [
    'en' => 'Please enter the verification code.',
    'ar' => 'يرجى إدخال رمز التحقق.'
],

'invalid_verification_code_format' => [
    'en' => 'Invalid code format. It must be 6 digits.',
    'ar' => 'تنسيق الرمز غير صحيح. يجب أن يكون مكوّنًا من 6 أرقام.'
],

'wrong_verification_code' => [
    'en' => 'The verification code is incorrect.',
    'ar' => 'رمز التحقق غير صحيح.'
],

'email_already_exists' => [
    'en' => 'This email is already registered.',
    'ar' => 'هذا البريد الإلكتروني مسجّل بالفعل.'
],

'registration_failed' => [
    'en' => 'Account registration failed. Please try again later.',
    'ar' => 'فشل تسجيل الحساب. يرجى المحاولة مرة أخرى لاحقًا.'
],

'account_verified_redirect' => [
    'en' => 'Your account has been verified. Redirecting to login...',
    'ar' => 'تم التحقق من حسابك. يتم الآن تحويلك لتسجيل الدخول...'
],

'no_pending_registration' => [
    'en' => 'No pending company registration found.',
    'ar' => 'لم يتم العثور على تسجيل شركة قيد الانتظار.'
],

'go_to_registration' => [
    'en' => 'Go to Registration',
    'ar' => 'الذهاب إلى التسجيل'
],

'code_sent_notice' => [
    'en' => 'A verification code was sent to',
    'ar' => 'تم إرسال رمز التحقق إلى'
],

'verification_code_label' => [
    'en' => 'Verification Code',
    'ar' => 'رمز التحقق'
],

'verification_code_title' => [
    'en' => 'Enter the 6-digit code from your email',
    'ar' => 'أدخل رمز التحقق المكوّن من 6 أرقام من بريدك الإلكتروني'
],

'verify_account_button' => [
    'en' => 'Verify Account',
    'ar' => 'تحقق من الحساب'
],

'didnt_receive_code' => [
    'en' => 'Didn’t receive the code?',
    'ar' => 'لم يصلك الرمز؟'
],

'resend_code_link' => [
    'en' => 'Resend Code',
    'ar' => 'إعادة إرسال الرمز'
],

'all_rights_reserved' => [
    'en' => 'All rights reserved.',
    'ar' => 'جميع الحقوق محفوظة.'
],

'price' => [
    'en' => 'Price',
    'ar' => 'السعر'
],

'public_profile' => [
    'en' => 'Public Profile',
    'ar' => 'الملف الشخصي العام'
],

'pending_company_products' => [
    'en' => 'Pending Company Products',
    'ar' => 'منتجات الشركات قيد الانتظار'
],
'approved_company_products' => [
    'en' => 'Approved Company Products',
    'ar' => 'منتجات الشركات المعتمدة'
],
'pending_products' => [
    'en' => 'Pending Products',
    'ar' => 'المنتجات المعلقة'
],
'approved_products' => [
    'en' => 'Approved Products',
    'ar' => 'المنتجات المعتمدة'
],
'product_name' => [
    'en' => 'Product Name',
    'ar' => 'اسم المنتج'
],
'category' => [
    'en' => 'Category',
    'ar' => 'الفئة'
],
'company_name' => [
    'en' => 'Company Name',
    'ar' => 'اسم الشركة'
],
'actions' => [
    'en' => 'Actions',
    'ar' => 'الإجراءات'
],
'view' => [
    'en' => 'View',
    'ar' => 'عرض'
],
'no_pending_products' => [
    'en' => 'No pending products found.',
    'ar' => 'لا توجد منتجات قيد الانتظار.'
],
'no_approved_products' => [
    'en' => 'No approved products found.',
    'ar' => 'لا توجد منتجات معتمدة.'
],
'price' => [
    'en' => 'Price',
    'ar' => 'السعر'
],
'jod' => [
    'en' => 'JOD',
    'ar' => 'دينار'
],
'product_details' => [
    'en' => 'Product Details',
    'ar' => 'تفاصيل المنتج'
],
'product_number' => [
    'en' => 'Product Number',
    'ar' => 'رقم المنتج'
],
'product_description' => [
    'en' => 'Product Description',
    'ar' => 'وصف المنتج'
],
'approve' => [
    'en' => 'Approve',
    'ar' => 'اعتماد'
],
'reject' => [
    'en' => 'Reject',
    'ar' => 'رفض'
],
'close' => [
    'en' => 'Close',
    'ar' => 'إغلاق'
],
'delete' => [
    'en' => 'Delete',
    'ar' => 'حذف'
],
'deactivate' => [
    'en' => 'Deactivate',
    'ar' => 'إلغاء التفعيل'
],
'confirm_delete' => [
    'en' => 'Confirm Deletion',
    'ar' => 'تأكيد الحذف'
],
'confirm_delete_product_message' => [
    'en' => 'Are you sure you want to delete this product?',
    'ar' => 'هل أنت متأكد أنك تريد حذف هذا المنتج؟'
],
'confirm_deactivate' => [
    'en' => 'Confirm Deactivation',
    'ar' => 'تأكيد إلغاء التفعيل'
],
'confirm_deactivate_product_message' => [
    'en' => 'Are you sure you want to deactivate this product?',
    'ar' => 'هل أنت متأكد أنك تريد إلغاء تفعيل هذا المنتج؟'
],
'confirm_reject_product' => [
    'en' => 'Are you sure you want to reject this product?',
    'ar' => 'هل أنت متأكد أنك تريد رفض هذا المنتج؟'
],
'product_approved_message' => [
    'en' => 'Your product "%s" has been approved and is now live on the platform.',
    'ar' => 'تم اعتماد منتجك "%s" وهو الآن ظاهر على المنصة.'
],
'product_deactivated_message' => [
    'en' => 'Your product "%s" has been deactivated by the admin.',
    'ar' => 'تم إلغاء تفعيل منتجك "%s" من قبل المشرف.'
],
'product_approved' => [
    'en' => 'Product approved successfully.',
    'ar' => 'تم اعتماد المنتج بنجاح.'
],
'product_deactivated' => [
    'en' => 'Product deactivated successfully.',
    'ar' => 'تم إلغاء تفعيل المنتج بنجاح.'
],
'product_rejected' => [
    'en' => 'Product rejected and removed.',
    'ar' => 'تم رفض المنتج وحذفه.'
],
'product_deleted' => [
    'en' => 'Product deleted successfully.',
    'ar' => 'تم حذف المنتج بنجاح.'
],

'no_vouchers_found' => [
    'en' => 'No Vouchers Found',
    'ar' => 'لا توجد قسائم شرائية'
],


'email_failed' => ['en' => 'Email could not be sent', 'ar' => 'تعذر إرسال البريد الإلكتروني'],

    // Products Section
    'your_products' => ['en' => 'Your Products', 'ar' => 'منتجاتك'],
    'add_product' => ['en' => 'Add Product', 'ar' => 'إضافة منتج'],
    'no_products' => ['en' => 'You haven\'t added any products yet.', 'ar' => 'لم تقم بإضافة أي منتجات بعد.'],

    // Comments Section
    'your_comments' => ['en' => 'Your Comments', 'ar' => 'تعليقاتك'],
    'no_comments' => ['en' => 'You haven\'t written any comments yet.', 'ar' => 'لم تقم بكتابة أي تعليقات بعد.'],
    'view_on_product' => ['en' => 'View on Product', 'ar' => 'عرض على المنتج'],

    'testimonial_header' => ['en' => 'What Our BuyWise Community Says', 'ar' => 'آراء مجتمع BuyWise'],
    'testimonial_subtitle' => ['en' => 'Real reviews from verified users who trust BuyWise for honest product recommendations', 'ar' => 'مراجعات حقيقية من مستخدمين موثوقين يثقون بـ BuyWise'],
    'quality' => ['en' => 'Quality', 'ar' => 'الجودة'],
    'verified_review' => ['en' => 'Verified Review', 'ar' => 'مراجعة موثقة'],
    'min_points_required' => ['en' => 'Points Required', 'ar' => 'النقاط المطلوبة'],


    // Footer

    // Popup
    'comment_delete_failed' => ['en' => 'Failed to delete comment.', 'ar' => 'فشل في حذف التعليق.'],
    'confirm_delete_comment' => ['en' => 'Are you sure you want to delete this comment?', 'ar' => 'هل أنت متأكد من حذف هذا التعليق؟'],
    'are_you_sure_delete_comment' => ['en' => 'This action cannot be undone. Are you sure?', 'ar' => 'لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد؟'],
    'confirm' => ['en' => 'Confirm', 'ar' => 'تأكيد'],

    'arabic' => ['en' => 'Arabic', 'ar' => 'العربية'],
    'english' => ['en' => 'English', 'ar' => 'الإنجليزية'],
    'discount_value' => ['en' => 'Discount Value', 'ar' => 'قيمة القسيمة'],
    'add_new_voucher' => ['en' => 'Add New Voucher', 'ar' => 'أضف قسيمة جديدة'],
    'your_vouchers' => ['en' => 'Your Vouchers', 'ar' => 'قسائمك الشرائية'],
    'voucher' => ['en' => 'Vouchers', 'ar' => 'القسائم'],
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Profile Overview
    'user_products' => ['en' => "{user}'s Products", 'ar' => 'منتجات {user}'],
    'user_comments' => ['en' => "{user}'s Comments", 'ar' => 'تعليقات {user}'],
    'go_to_your_dashboard' => ['en' => 'Go to Your Dashboard', 'ar' => 'الذهاب إلى لوحة التحكم الخاصة بك'],

    // Messages
    'no_user_products' => ['en' => 'This user hasn\'t added any products yet.', 'ar' => 'هذا المستخدم لم يقم بإضافة أي منتجات بعد.'],
    'no_user_comments' => ['en' => 'This user hasn\'t made any comments yet.', 'ar' => 'هذا المستخدم لم يكتب أي تعليقات بعد.'],
    'invalid_user_id' => ['en' => 'Invalid user ID.', 'ar' => 'معرف المستخدم غير صالح.'],
    'user_not_found' => ['en' => 'User not found.', 'ar' => 'المستخدم غير موجود.'],

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Reset Password Page
    'enter_new_password' => ['en' => 'Please enter your new password below.', 'ar' => 'يرجى إدخال كلمة المرور الجديدة أدناه.'],
    'update_password' => ['en' => 'Update Password', 'ar' => 'تحديث كلمة المرور'],
    'password_requirements' => ['en' => 'Password must be at least 8 characters, include uppercase, lowercase, number, and special character.', 'ar' => 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل، وتشمل حرفًا كبيرًا وصغيرًا ورقمًا ورمزًا خاصًا.'],

    // Validation Errors
    'error_passwords_do_not_match' => ['en' => 'Passwords do not match.', 'ar' => 'كلمتا المرور غير متطابقتين.'],

    // Feedback / Alerts
    'password_reset_success' => ['en' => 'Password reset successfully.', 'ar' => 'تمت إعادة تعيين كلمة المرور بنجاح.'],
    'login_now' => ['en' => 'Log in now', 'ar' => 'تسجيل الدخول الآن'],
    'invalid_or_expired_link' => ['en' => 'This link is invalid or has expired.', 'ar' => 'هذا الرابط غير صالح أو انتهت صلاحيته.'],
    'missing_token' => ['en' => 'Missing token. Please use the link sent to your email.', 'ar' => 'رمز مفقود. يرجى استخدام الرابط المرسل إلى بريدك الإلكتروني.'],
    'try_again' => ['en' => 'Try Again', 'ar' => 'حاول مرة أخرى'],
    'success' => ['en' => 'Success', 'ar' => 'نجاح'],
    'error' => ['en' => 'Error', 'ar' => 'خطأ'],

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    'search_results_title' => ['en' => 'Search Results', 'ar' => 'نتائج البحث'],
    'search_results_for' => ['en' => 'Search Results for', 'ar' => 'نتائج البحث عن'],
    'filter_by_rating' => ['en' => 'Filter by Rating:', 'ar' => 'تصفية حسب التقييم:'],
    'all_ratings' => ['en' => 'All Ratings', 'ar' => 'جميع التقييمات'],
    'stars_only' => ['en' => 'stars only', 'ar' => 'نجوم فقط'],
    'stars_and_up' => ['en' => 'stars & up', 'ar' => 'نجوم فأكثر'],
    'apply_filter' => ['en' => 'Apply', 'ar' => 'تطبيق'],
    'back' => ['en' => '← Back', 'ar' => '← رجوع'],
    'rating' => ['en' => 'Rating', 'ar' => 'التقييم'],
    'view_product' => ['en' => 'View Product', 'ar' => 'عرض المنتج'],
    'please_enter_search_term' => ['en' => 'Please enter a search term.', 'ar' => 'يرجى إدخال مصطلح للبحث.'],

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    'no_comments_available' => ['en' => 'There are no comments available for', 'ar' => 'لا توجد تعليقات متاحة لـ'],
    'comment_no' => ['en' => 'No', 'ar' => 'الرقم'],
    'comment_name' => ['en' => 'Comment', 'ar' => 'التعليق'],
    'comment_date' => ['en' => 'Date', 'ar' => 'التاريخ'],
    'settings' => ['en' => 'Settings', 'ar' => 'الإعدادات'],

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    'no_products_in_category' => ['en' => 'There are no products available in', 'ar' => 'لا توجد منتجات متاحة في فئة'],
    'no' => ['en' => 'No', 'ar' => 'الرقم'],
    'select_product_name' => ['en' => 'Select Product Name', 'ar' => 'اختر اسم المنتج'],

    'liked_your_comment' => ['en' => 'liked your comment.', 'ar' => 'أعجب بتعليقك.'],
    'disliked_your_comment' => ['en' => 'disliked your comment.', 'ar' => 'لم يعجبه تعليقك.'],
    'db_connection_failed' => ['en' => 'Database connection failed', 'ar' => 'فشل الاتصال بقاعدة البيانات'],
    'invalid_parameters' => ['en' => 'Invalid parameters', 'ar' => 'معلمات غير صالحة'],

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    'database_connection_failed' => ['en' => 'Database connection failed', 'ar' => 'فشل الاتصال بقاعدة البيانات'],
    'user_data_not_found' => ['en' => 'User data not found.', 'ar' => 'لم يتم العثور على بيانات المستخدم.'],
    'password_update_failed' => ['en' => 'Failed to update password.', 'ar' => 'فشل تحديث كلمة المرور.'],
    'invalid_image_file' => ['en' => 'The uploaded file is not a valid image.', 'ar' => 'الملف المرفوع ليس صورة صالحة.'],
    'user_update_failed' => ['en' => 'Failed to update user details.', 'ar' => 'فشل تحديث بيانات المستخدم.'],
    'login_again_after_password' => ['en' => 'Your password has been updated. Please log in with your new password.', 'ar' => 'تم تحديث كلمة المرور الخاصة بك. الرجاء تسجيل الدخول باستخدام كلمة المرور الجديدة.'],

    // Form Labels
    'birth_date' => ['en' => 'Birth Date', 'ar' => 'تاريخ الميلاد'],
    'avatar' => ['en' => 'Avatar', 'ar' => 'الصورة الشخصية'],
    'bio' => ['en' => 'Bio', 'ar' => 'نبذة شخصية'],
    'update_information' => ['en' => 'Update Information', 'ar' => 'تحديث المعلومات'],
    'delete_account' => ['en' => 'Delete Account', 'ar' => 'حذف الحساب'],
    'confirm_delete_account_title' => ['en' => 'Confirm Account Deletion', 'ar' => 'تأكيد حذف الحساب'],
    'delete_account_warning' => ['en' => 'This action is irreversible. All your data will be permanently removed.', 'ar' => 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع بياناتك نهائيًا.'],
    'yes_delete' => ['en' => 'Yes, Delete', 'ar' => 'نعم، احذف'],
    'no_cancel' => ['en' => 'No, Cancel', 'ar' => 'لا، إلغاء'],
    'no_undo' => ['en' => 'This action cannot be undone.', 'ar' => 'لا يمكن التراجع عن هذا الإجراء.'],



    // Popup / messages
    'information_updated_success' => ['en' => 'Information updated successfully!', 'ar' => 'تم تحديث المعلومات بنجاح!'],
    'changing_password_alert' => ['en' => 'Changing your password will require you to log in again.', 'ar' => 'تغيير كلمة المرور سيتطلب تسجيل الدخول مجددًا.'],

    'status_update_success' => ['en' => 'Status updated successfully', 'ar' => 'تم تحديث الحالة بنجاح'],
    'status_update_failed' => ['en' => 'Failed to update status', 'ar' => 'فشل في تحديث الحالة'],
    'comment_deleted_success' => ['en' => 'Comment deleted successfully', 'ar' => 'تم حذف التعليق بنجاح'],
    'go_back' => ['en' => 'Go Back', 'ar' => 'الرجوع'],

    'verify_email' => ['en' => 'Verify Your Email', 'ar' => 'تأكيد البريد الإلكتروني'],
    'verification_code_subject' => ['en' => 'Your BuyWise Verification Code', 'ar' => 'رمز التحقق من BuyWise'],
    'your_verification_code' => ['en' => 'Your verification code is', 'ar' => 'رمز التحقق الخاص بك هو'],
    'resend_failed' => ['en' => 'Failed to resend the code. Please try again.', 'ar' => 'فشل في إرسال الرمز. حاول مرة أخرى.'],
    'code_resent_success' => ['en' => 'A new code has been sent to your email.', 'ar' => 'تم إرسال رمز جديد إلى بريدك الإلكتروني.'],
    'enter_code_placeholder' => ['en' => 'Enter verification code', 'ar' => 'أدخل رمز التحقق'],
    'verify' => ['en' => 'Verify', 'ar' => 'تحقق'],
    'resend_code' => ['en' => 'Resend Code', 'ar' => 'إعادة إرسال الرمز'],
    'registration_failed' => ['en' => 'Registration failed', 'ar' => 'فشل في إنشاء الحساب'],
    'invalid_verification_code' => ['en' => 'Invalid verification code', 'ar' => 'رمز التحقق غير صحيح'],

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    'hero_title' => ['en' => 'Discover and Share Trusted Product Reviews', 'ar' => 'اكتشف وشارك مراجعات المنتجات الموثوقة'],
    'hero_subtitle' => ['en' => 'Empowering your purchase decisions with real user feedback.', 'ar' => 'نساعدك على اتخاذ قرارات شراء أفضل من خلال تجارب المستخدمين الفعلية.'],
    'hero_join' => ['en' => 'Join Now', 'ar' => 'انضم الآن'],
    'hero_explore' => ['en' => 'Explore Products', 'ar' => 'استعرض المنتجات'],
    'testimonials_title' => ['en' => 'What Our BuyWise Community Says', 'ar' => 'ماذا يقول مجتمع باي وايز'],
    'testimonials_subtitle' => ['en' => 'Real reviews from verified users who trust BuyWise for honest product recommendations', 'ar' => 'مراجعات حقيقية من مستخدمين موثوقين يعتمدون على باي وايز للتوصيات الصادقة'],
    'featured_products' => ['en' => 'Featured Products', 'ar' => 'المنتجات المميزة'],
    'categories_title' => ['en' => 'Popular Categories', 'ar' => 'الفئات الشائعة'],

    'trusted_brands' => ['en' => 'Trusted Brands', 'ar' => 'العلامات التجارية الموثوقة'],
    'verified' => ['en' => 'Verified', 'ar' => 'موثوق'],
    'how_it_works' => ['en' => 'How It Works', 'ar' => 'كيف تعمل المنصة'],
    'step_1' => ['en' => '1. Sign Up & Verify', 'ar' => '١. أنشئ حسابًا وفعّله'],
    'step_2' => ['en' => '2. Explore Products', 'ar' => '٢. استعرض المنتجات'],
    'step_3' => ['en' => '3. Write Reviews', 'ar' => '٣. اكتب المراجعات'],
    'join_community' => ['en' => 'Be Part of the BuyWise Community', 'ar' => 'كن جزءًا من مجتمع باي وايز'],
    'video_not_supported' => ['en' => 'Your browser does not support the video tag.', 'ar' => 'متصفحك لا يدعم تشغيل الفيديو.'],

    'about_us_title' => ['en' => 'About BuyWise', 'ar' => 'حول BuyWise'],
    'about_us_text' => ['en' => 'BuyWise is a review platform that allows users to share honest feedback and earn rewards for trusted reviews.', 'ar' => 'BuyWise هو منصة مراجعات تتيح للمستخدمين مشاركة آرائهم الصادقة والحصول على مكافآت للمراجعات الموثوقة.'],

    'goals_title' => ['en' => 'Our Goals', 'ar' => 'أهدافنا'],

    'goal_1_title' => ['en' => 'Safety', 'ar' => 'الأمان'],
    'goal_1_desc' => ['en' => 'Ensure user privacy and secure data handling.', 'ar' => 'ضمان خصوصية المستخدم ومعالجة البيانات بأمان.'],

    'goal_2_title' => ['en' => 'Reach', 'ar' => 'الوصول'],
    'goal_2_desc' => ['en' => 'Expand product discovery for all users.', 'ar' => 'توسيع اكتشاف المنتجات لجميع المستخدمين.'],

    'goal_3_title' => ['en' => 'Education', 'ar' => 'التثقيف'],
    'goal_3_desc' => ['en' => 'Provide informative reviews and insights.', 'ar' => 'توفير مراجعات ومعلومات تثقيفية.'],

    'goal_4_title' => ['en' => 'Community', 'ar' => 'المجتمع'],
    'goal_4_desc' => ['en' => 'Build a trustworthy review network.', 'ar' => 'بناء شبكة مراجعات موثوقة.'],

    'goal_5_title' => ['en' => 'Recognition', 'ar' => 'التميّز'],
    'goal_5_desc' => ['en' => 'Reward valuable and honest contributions.', 'ar' => 'مكافأة المساهمات القيمة والصادقة.'],

    'goal_6_title' => ['en' => 'Insight', 'ar' => 'الرؤية'],
    'goal_6_desc' => ['en' => 'Help users make informed choices.', 'ar' => 'مساعدة المستخدمين على اتخاذ قرارات مدروسة.'],

    'back_to_top' => ['en' => 'Back to Top', 'ar' => 'العودة للأعلى'],

    'search_placeholder' => ['en' => 'Search...', 'ar' => 'ابحث...'],
    'more' => ['en' => 'More', 'ar' => 'المزيد'],
    'faq' => ['en' => 'FAQ', 'ar' => 'الأسئلة الشائعة'],

    'profile' => ['en' => 'Profile', 'ar' => 'الملف الشخصي'],
    'logout' => ['en' => 'Logout', 'ar' => 'تسجيل الخروج'],

    'notifications' => ['en' => 'Notifications', 'ar' => 'الإشعارات'],
    'view_all' => ['en' => 'View All', 'ar' => 'عرض الكل'],
    'no_notifications' => ['en' => 'No notifications yet.', 'ar' => 'لا توجد إشعارات بعد.'],


    'ban' => ['en' => 'Ban', 'ar' => 'حظر'],
    'fake_reviews' => ['en' => 'Fake', 'ar' => 'مزيفة'],
    'real_reviews' => ['en' => 'Real', 'ar' => 'حقيقية'],
    'total_reviews' => ['en' => 'Total', 'ar' => 'الإجمالي'],
    'last_reported' => ['en' => 'Last Report', 'ar' => 'آخر بلاغ'],
    'unverified_reviews' => ['en' => 'Unverified', 'ar' => 'غير المؤكدة'],
    'remaining' => ['en' => 'Remaining', 'ar' => 'المتبقي للحظر'],


    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    'account_settings' => ['en' => 'Account Settings', 'ar' => 'إعدادات الحساب'],
    'choose_category' => ['en' => 'Choose a category', 'ar' => 'اختر فئة'],
    'company_logo' => ['en' => 'Company Logo', 'ar' => 'شعار الشركة'],
    'company_name' => ['en' => 'Company Name', 'ar' => 'اسم الشركة'],
    'error_database' => ['en' => 'Database error. Please try again.', 'ar' => 'خطأ في قاعدة البيانات. حاول مرة أخرى.'],
    'error_missing_fields' => ['en' => 'Please fill in all required fields.', 'ar' => 'يرجى تعبئة جميع الحقول المطلوبة.'],
    'error_upload' => ['en' => 'Failed to upload file.', 'ar' => 'فشل في رفع الملف.'],
    'file_too_large' => ['en' => 'File size exceeds 2MB.', 'ar' => 'حجم الملف يتجاوز 2 ميغابايت.'],
    'invalid_file_type' => ['en' => 'Invalid file type.', 'ar' => 'نوع الملف غير صالح.'],
    'pending' => ['en' => 'Pending', 'ar' => 'قيد الانتظار'],
    'price' => ['en' => 'Price', 'ar' => 'السعر'],
    'product_already_exists' => ['en' => 'Product already exists.', 'ar' => 'المنتج موجود بالفعل.'],
    'product_price' => ['en' => 'Product Price', 'ar' => 'سعر المنتج'],
    'product_submitted' => ['en' => 'Product submitted successfully.', 'ar' => 'تم إرسال المنتج بنجاح.'],
    'rejected' => ['en' => 'Rejected', 'ar' => 'مرفوض'],
    'submit_product' => ['en' => 'Submit Product', 'ar' => 'إرسال المنتج'],
    'update' => ['en' => 'Update', 'ar' => 'تحديث'],
    'currency_jod' => [
    'en' => 'JOD',
    'ar' => 'دينار أردني'
    ],

    'rewards_center' => ['en' => 'Rewards Center', 'ar' => 'مركز المكافآت'],
    'your_points' => ['en' => 'Your Points', 'ar' => 'نقاطك'],
    'voucher_code' => ['en' => 'Voucher Code', 'ar' => 'رمز القسيمة'],
    'points_required' => ['en' => 'Points Required', 'ar' => 'النقاط المطلوبة'],
    'expiry_date' => ['en' => 'Expiry Date', 'ar' => 'تاريخ الانتهاء'],
    'action' => ['en' => 'Action', 'ar' => 'الإجراء'],
    'redeem_now' => ['en' => 'Redeem Now', 'ar' => 'استبدل الآن'],
    'no_vouchers_available' => ['en' => 'No vouchers available at the moment.', 'ar' => 'لا توجد قسائم متاحة حالياً.'],
    'voucher_redeemed_success' => ['en' => 'Voucher redeemed successfully!', 'ar' => 'تم استبدال القسيمة بنجاح!'],
    'voucher_already_redeemed' => ['en' => 'You have already redeemed this voucher.', 'ar' => 'لقد قمت باستبدال هذه القسيمة مسبقًا.'],
    'voucher_redeem_failed' => ['en' => 'You do not have enough points to redeem this voucher.', 'ar' => 'ليس لديك نقاط كافية لاستبدال هذه القسيمة.'],
    // Upgrade Plan Page
    'upgrade_title' => ['en' => 'Upgrade to Pro', 'ar' => 'الترقية إلى Pro'],
    'upgrade_subtitle' => ['en' => 'Take your experience to the next level', 'ar' => 'ارتقِ بتجربتك إلى المستوى التالي'],
    'pro_plan' => ['en' => 'Pro Plan', 'ar' => 'الخطة الاحترافية'],
    'price_per_month' => ['en' => '$30 / month', 'ar' => '30 دولار / شهريًا'],
    'unlimited_uploads' => ['en' => 'Unlimited Product Uploads', 'ar' => 'رفع غير محدود للمنتجات'],
    'unlimited_uploads_desc' => ['en' => 'Add as many products as you want without any restrictions', 'ar' => 'ارفع ما تشاء من المنتجات بدون قيود'],
    'ai_validation' => ['en' => 'AI Validation for Non-English Reviews', 'ar' => 'تحقق بالذكاء الاصطناعي من التقييمات غير الإنجليزية'],
    'ai_validation_desc' => ['en' => 'Our AI automatically validates reviews in multiple languages', 'ar' => 'الذكاء الاصطناعي يتحقق تلقائيًا من التقييمات بلغات متعددة'],
    'ai_detection' => ['en' => 'AI Detection of Fake Products', 'ar' => 'كشف المنتجات المزيفة بالذكاء الاصطناعي'],
    'ai_detection_desc' => ['en' => 'Advanced protection against counterfeit listings', 'ar' => 'حماية متقدمة من المنتجات المزيفة'],
    'coming_soon' => ['en' => 'Coming Soon', 'ar' => 'قريبًا'],

    // AddProduct messages
    'product_exists' => ['en' => 'Product already exists.', 'ar' => 'هذا المنتج موجود بالفعل.'],
    'product_submitted' => ['en' => 'Product submitted and is awaiting admin approval.', 'ar' => 'تم إرسال المنتج وهو بانتظار موافقة المشرف.'],
    'image_required' => ['en' => 'Main image is required.', 'ar' => 'الصورة الرئيسية مطلوبة.'],
    'image_invalid' => ['en' => 'Invalid image type.', 'ar' => 'نوع الصورة غير صالح.'],
    'image_large' => ['en' => 'Image is too large.', 'ar' => 'حجم الصورة كبير جدًا.'],
    'daily_limit' => ['en' => 'Daily limit reached. Upgrade to Pro for unlimited uploads.', 'ar' => '⏳ تم الوصول للحد اليومي. قم بالترقية إلى Pro للرفع غير المحدود.'],
    'account_banned' => ['en' => 'Your account has been deactivated due to fake reviews. You will now be logged out.', 'ar' => 'تم تعطيل حسابك بسبب تقييمات مزيفة. سيتم تسجيل خروجك الآن.'],
    'improve_review' => ['en' => 'Please improve your review by writing in clear English and providing more details.', 'ar' => 'يرجى تحسين التقييم بكتابة إنجليزية واضحة وتقديم تفاصيل أكثر.'],
    'upload_failed' => ['en' => 'Upload failed.', 'ar' => 'فشل في رفع المنتج.'],
    'upgrade' => ['en' => 'Upgrade', 'ar' => 'الترقية'],
    'ok' => ['en' => 'OK', 'ar' => 'حسناً'],
    'upload_failed' => [
        'en' => 'Upload failed.',
        'ar' => 'فشل في رفع المنتج.'
    ],
    'product_name_no_numbers' => [
    'en' => 'Product name must not contain numbers.',
    'ar' => 'لا يجب أن يحتوي اسم المنتج على أرقام.'
],
'main_image_required' => [
    'en' => 'Main product image is required.',
    'ar' => 'الصورة الرئيسية للمنتج مطلوبة.'
],


'is_local' => [
    'en' => 'Is this a local product?',
    'ar' => 'هل هذا المنتج محلي؟'
],
'yes' => [
    'en' => 'Yes',
    'ar' => 'نعم'
],
'no' => [
    'en' => 'No',
    'ar' => 'لا'
],
'local_product_number' => [
    'en' => 'Local Product Number',
    'ar' => 'رقم المنتج المحلي'
],
'enter_local_number' => [
    'en' => 'Enter local product number',
    'ar' => 'أدخل رقم المنتج المحلي'
],
'local_verified' => [
    'en' => 'Local Verified',
    'ar' => 'منتج محلي موثوق'
],

'admin_fake_content' => [
    'en' => 'Fake Content',
    'ar' => 'إدارة المحتوى المزيف'
],
'admin_comments_reports' => [
    'en' => 'Comments & Reports',
    'ar' => 'التعليقات والبلاغات'
],
'badge_professional' => ['en' => 'Professional (500+ points)', 'ar' => 'محترف (أكثر من 500 نقطة)'],
'badge_expert' => ['en' => 'Expert (1,500+ points)', 'ar' => 'خبير (أكثر من 1500 نقطة)'],
'badge_legend' => ['en' => 'Legend (5,000+ points)', 'ar' => 'أسطورة (أكثر من 5000 نقطة)'],

'confirm_delete_title' => [
    'en' => 'Confirm Deletion',
    'ar' => 'تأكيد الحذف'
],
'confirm_delete_message' => [
    'en' => 'Are you sure you want to delete this product? This action cannot be undone.',
    'ar' => 'هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.'
],
'confirm' => [
    'en' => 'Confirm',
    'ar' => 'تأكيد'
],
'cancel' => [
    'en' => 'Cancel',
    'ar' => 'إلغاء'
],
'success' => [
    'en' => 'Success',
    'ar' => 'تم بنجاح'
],
'product_deleted_successfully' => [
    'en' => 'Product deleted successfully!',
    'ar' => 'تم حذف المنتج بنجاح!'
],
'product_awaiting_approval' => [
    'en' => 'Your product has been submitted and will be reviewed by the admin for approval.',
    'ar' => 'تم إرسال المنتج بنجاح وسيتم مراجعته من قِبل الإدارة للموافقة عليه.'
],

'points' => ['en' => 'points', 'ar' => 'نقطة'],



    //products page
    'home' => ['en' => 'Home', 'ar' => 'الرئيسية'],
    'posted_by' => ['en' => 'Posted by', 'ar' => 'نشر بواسطة'],
    'category' => ['en' => 'Category', 'ar' => 'الفئة'],
    'rating' => ['en' => 'Rating', 'ar' => 'التقييم'],
    'reviews' => ['en' => 'Reviews', 'ar' => 'المراجعات'],
    'quality' => ['en' => 'Quality', 'ar' => 'الجودة'],
    'view_all_reviews' => ['en' => 'View All Reviews', 'ar' => 'عرض كل المراجعات'],
    'hide_reviews' => ['en' => 'Hide Reviews', 'ar' => 'إخفاء المراجعات'],
    'add_your_review' => ['en' => 'Add Your Review', 'ar' => 'أضف تقييمك'],
    'your_rating' => ['en' => 'Your Rating', 'ar' => 'تقييمك'],
    'write_review_here' => ['en' => 'Write your review here...', 'ar' => 'اكتب تقييمك هنا...'],
    'upload_image_optional' => ['en' => 'Upload an image (optional)', 'ar' => 'أرفق صورة (اختياري)'],
    'login_to_review' => ['en' => 'Login to Post a Review', 'ar' => 'سجل الدخول لكتابة تقييم'],
    'add_review' => ['en' => 'Add Review', 'ar' => 'أضف تقييمك'],
    'login_required' => ['en' => 'Login Required', 'ar' => 'مطلوب تسجيل الدخول'],
    'please_login_to_review' => ['en' => 'Please login to your account to add a review!', 'ar' => 'يرجى تسجيل الدخول لإضافة تقييم!'],
    'empty_review' => ['en' => 'Empty Review', 'ar' => 'التقييم فارغ'],
    'submitted' => ['en' => 'Submitted', 'ar' => 'تم الإرسال'],
    'error_occurred' => ['en' => 'Error occurred', 'ar' => 'حدث خطأ'],
    'back_to_top' => ['en' => 'Back to Top', 'ar' => 'العودة للأعلى'],
    'error' => ['en' => 'Error','ar' => 'خطأ'],
    'review_add_failed' => ['en' => "Review couldn't be added. Please try again.",'ar' => 'لم يتمكن من إضافة التقييم، حاول مرة أخرى'],
    'server_error' => ['en' => 'Server Error','ar' => 'خطأ في الخادم'],
    'try_again_later' => ['en' => 'An error occurred. Please try again later.','ar' => 'حدث خطأ، يرجى المحاولة لاحقًا'],
    'missing_info' => ['en' => 'Missing Information','ar' => 'معلومات ناقصة'],
    'select_both_rating_quality' => ['en' => 'Please select both a star rating and a quality level.','ar' => 'يرجى اختيار تقييم النجوم والجودة معًا'],
    'missing_rating' => ['en' => 'Missing Rating','ar' => 'التقييم مفقود'],
    'missing_quality' => ['en' => 'Missing Quality','ar' => 'الجودة مفقودة'],
    'submitted' => ['en' => 'Submitted','ar' => 'تم الإرسال'],
    'select_quality_level' => ['en' => 'Please select a quality level.','ar' => 'يرجى اختيار مستوى الجودة.'],
    'select_star_rating' => ['en' => 'Please select a star rating.','ar' => 'يرجى اختيار تقييم بالنجوم.'],
    'failed' => ['en' => 'Failed','ar' => 'فشل'],
    'invalid_response' => ['en' => 'Invalid server response','ar' => 'استجابة غير صالحة من الخادم'],
    'try_again_later' => ['en' => 'An error occurred. Please try again later.','ar' => 'حدث خطأ، يرجى المحاولة لاحقًا'],
    'no_reviews' => ['en' => 'No reviews yet.','ar' => 'لا توجد مراجعات بعد.'],
    'be_first_to_review' => ['en' => 'Be the first to review this product!','ar' => 'كن أول من يقيّم هذا المنتج!'],
    'write_your_reply' => ['en' => 'Write your reply...','ar' => 'اكتب ردك...'],
    'filter_by_rating' => ['en' => 'Filter by Rating:', 'ar' => 'تصفية حسب التقييم:'],
    'all_ratings' => ['en' => 'All', 'ar' => 'الكل'],
    'stars_only' => ['en' => 'stars only', 'ar' => 'نجوم فقط'],
    'stars_up' => ['en' => 'stars & up', 'ar' => 'نجوم فأكثر'],
    'sort_by' => ['en' => 'Sort by:', 'ar' => 'ترتيب حسب:'],
    'latest' => ['en' => 'Latest', 'ar' => 'الأحدث'],
    'oldest' => ['en' => 'Oldest', 'ar' => 'الأقدم'],
    'most_liked' => ['en' => 'Most Liked', 'ar' => 'الأكثر إعجابًا'],
    'apply_filters' => ['en' => 'Apply', 'ar' => 'تطبيق'],
    'reset_filters' => ['en' => 'Reset', 'ar' => 'إعادة تعيين'],
    'see_what_others_say' => ['en' => 'See what other customers are saying', 'ar' => 'شاهد آراء العملاء الآخرين'],
    'customer_reviews' => ['en' => 'Customer Reviews','ar' => 'مراجعات العملاء'],
    'excellent' => ['en' => 'Excellent', 'ar' => 'ممتاز'],
    'very_good' => ['en' => 'Very Good', 'ar' => 'جيد جدًا'],
    'good' => ['en' => 'Good', 'ar' => 'جيد'],
    'fair' => ['en' => 'Fair', 'ar' => 'مقبول'],
    'poor' => ['en' => 'Poor', 'ar' => 'ضعيف'],
    'not_rated' => ['en' => 'Not Rated', 'ar' => 'لم يُقيّم'],
    'reply' => ['en' => 'Reply','ar' => 'رد'],
    'report' => ['en' => 'Report','ar' => 'إبلاغ'],
    'post_reply' => ['en' => 'Post','ar' => 'إرسال'],
    'choose_image' => ['en' => 'Choose an image', 'ar' => 'اختر صورة'],
    'select_option' => ['en' => '-- Select --', 'ar' => '-- اختر --'],


    //badges
    'badge_normal' => ['en' => 'Normal','ar' => 'مبتدئ'],
    'badge_professional' => ['en' => 'Professional','ar' => 'محترف'],
    'badge_expert' => ['en' => 'Expert','ar' => 'خبير'],
    'badge_legend' => ['en' => 'Legend','ar' => 'أسطورة'],
    'points' => ['en' => 'pts','ar' => 'نقطة' ],

    //Admin Manage Companies
'product_approved_message' => ['en' => 'Your product "%s" has been approved by the admin.','ar' => 'تمت الموافقة على منتجك "%s" من قبل المسؤول.'],
'product_approved' => ['en' => 'Product approved successfully.','ar' => 'تمت الموافقة على المنتج بنجاح.'],
'product_rejected_message' => ['en' => 'Your product "%s" has been rejected by the admin.','ar' => 'تم رفض منتجك "%s" من قبل المسؤول.'],
'product_rejected' => ['en' => 'Product rejected successfully.','ar' => 'تم رفض المنتج بنجاح.'],
'pending_company_products' => ['en' => 'Pending Company Products','ar' => 'المنتجات المرسلة من الشركات' ],
'no_pending_products' => ['en' => 'There are no pending products.','ar' => 'لا توجد منتجات معلّقة.'],
'product_number' => ['en' => 'Product Number','ar' => 'رقم المنتج'],
'confirm_reject_product' => ['en' => 'Are you sure you want to reject this product?','ar' => 'هل أنت متأكد من رفض هذا المنتج؟'],

    //Admin Manage Comments
'date' => ['en' => 'Date','ar' => 'التاريخ'],

    //Admin Manage Pending user products
'pending_user_products' => ['en' => 'Pending User Products','ar' => 'منتجات المستخدمين المعلقة'],
// في ملف lang.php
'empty_product_description' => [
    'en' => 'Please enter a product description before submitting.',
    'ar' => 'يرجى إدخال وصف المنتج قبل الإرسال.'
],
'unverified_review' => [
    'en' => 'Unverified Review',
    'ar' => 'مراجعة غير موثقة'
],


// في lang.php
'date_placeholder' => [
    'en' => 'YYYY-MM-DD',
    'ar' => 'سنة-شهر-يوم'
],
'birth_date' => [
    'en' => 'Birth Date',
    'ar' => 'تاريخ الميلاد'
],

//Company dashboard
'product_with_count' => [
    'en' => 'products',
    'ar' => 'منتجات' // فقط لل fallback، لن تُستخدم مع الدالة
],

'add_voucher' => [
    'en' => 'Add Voucher',
    'ar' => 'إضافة قسيمة'
],
'delete_product_title' => [
    'en' => 'Delete Product',
    'ar' => 'حذف المنتج'
],
'delete_product_message' => [
    'en' => 'Are you sure you want to delete this product? This action cannot be undone.',
    'ar' => 'هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.'
],
'product_deleted_success' => [
    'en' => 'Product deleted successfully.',
    'ar' => 'تم حذف المنتج بنجاح.'
],
'error_deleting_product' => [
    'en' => 'Failed to delete the product.',
    'ar' => 'فشل في حذف المنتج.'
],
    'unauthorized' => [
        'en' => 'Unauthorized',
        'ar' => 'غير مصرح به'
    ],
    'missing_fields' => [
        'en' => 'Missing required fields',
        'ar' => 'الحقول المطلوبة مفقودة'
    ],
    'unexpected_ai_response' => [
        'en' => 'Unexpected AI response',
        'ar' => 'استجابة غير متوقعة من الذكاء الاصطناعي'
    ],
    'improve_review_error' => [
        'en' => 'Please write a more detailed review in your preferred language.',
        'ar' => 'يرجى كتابة مراجعة أكثر تفصيلاً بلغتك المفضلة.'
    ],
    'review_flagged_fake' => [
        'en' => 'Your recent review was flagged as potentially inauthentic.',
        'ar' => 'تم تصنيف مراجعتك الأخيرة على أنها قد تكون غير حقيقية.'
    ],
    'review_earned_points' => [
        'en' => 'You earned 6 points for reviewing a Local product.',
        'ar' => 'لقد حصلت على 6 نقاط لمراجعتك منتجاً محلياً.'
    ],
    'review_flagged_message' => [
        'en' => 'Your review was flagged as fake.',
        'ar' => 'تم الإبلاغ عن مراجعتك على أنها مزيفة.'
    ],
    'account_temp_deactivated' => [
        'en' => 'Your account has been temporarily deactivated.',
        'ar' => 'تم تعطيل حسابك مؤقتاً.'
    ],
    'account_permanently_deleted' => [
        'en' => 'Your account has been permanently deleted.',
        'ar' => 'تم حذف حسابك نهائيًا.'
    ],
    'comment_added_points_updated' => [
        'en' => 'Comment added and points updated successfully.',
        'ar' => 'تمت إضافة التعليق وتحديث النقاط بنجاح.'
    ],
    'commented_on_product' => [
        'en' => 'commented on your product.',
        'ar' => 'علق على منتجك.'
    ],

// Comment & reply messages
'empty_comment' => [
    'en' => 'Empty comment',
    'ar' => 'التعليق فارغ'
],
'parent_comment_not_found' => [
    'en' => 'Parent comment not found',
    'ar' => 'لم يتم العثور على التعليق الأصلي'
],
'replied_to_comment' => [
    'en' => 'replied to your comment.',
    'ar' => 'رد على تعليقك.'
],
'reply_insert_failed' => [
    'en' => 'Failed to insert reply',
    'ar' => 'فشل في إضافة الرد'
],

    // Add New Products
    'empty_product_description' => [
        'en' => 'Product description cannot be empty.',
        'ar' => 'وصف المنتج لا يمكن أن يكون فارغاً.'
    ],
    'image_required' => [
        'en' => 'Main product image is required.',
        'ar' => 'يجب تحميل صورة المنتج الرئيسية.'
    ],
    'image_invalid' => [
        'en' => 'Invalid image format.',
        'ar' => 'تنسيق الصورة غير صالح.'
    ],
    'image_large' => [
        'en' => 'Image size exceeds 2MB.',
        'ar' => 'حجم الصورة يتجاوز 2 ميجابايت.'
    ],
    'product_exists' => [
        'en' => 'You have already submitted this product.',
        'ar' => 'لقد قمت بإضافة هذا المنتج من قبل.'
    ],
    'product_submitted' => [
        'en' => 'Product submitted successfully!',
        'ar' => 'تم إرسال المنتج بنجاح!'
    ],
    'upload_failed' => [
        'en' => 'Upload failed. Please try again.',
        'ar' => 'فشل التحميل. يرجى المحاولة مرة أخرى.'
    ],
    'account_banned' => [
        'en' => 'Your account has been banned due to repeated fake submissions.',
        'ar' => 'تم حظر حسابك بسبب التكرار في رفع محتوى مزيف.'
    ],
    'improve_review' => [
        'en' => 'Please write a more detailed description in your preferred language.',
        'ar' => 'يرجى كتابة وصف أكثر تفصيلاً باللغة المفضلة لديك.'
    ],
    'only_first_images' => [
        'en' => 'Only the first {count} images will be uploaded. You selected {selected}.',
        'ar' => 'سيتم تحميل أول {count} صورة فقط. لقد اخترت {selected}.'
    ],
    'main_image_required' => [
        'en' => 'Main image is required.',
        'ar' => 'الصورة الرئيسية مطلوبة.'
    ],
    'product_added' => [
        'en' => 'Product has been added.',
        'ar' => 'تمت إضافة المنتج.'
    ],
    'invalid_image_type' => [
        'en' => 'Invalid image type.',
        'ar' => 'نوع الصورة غير صالح.'
    ],
    'image_too_large' => [
        'en' => 'Image file is too large.',
        'ar' => 'ملف الصورة كبير جداً.'
    ],
    'must_not_contain_numbers' => [
        'en' => 'Name must not contain numbers.',
        'ar' => 'يجب ألا يحتوي الاسم على أرقام.'
    ],
    'daily_limit' => [
        'en' => 'You have reached the daily submission limit.',
        'ar' => 'لقد وصلت إلى الحد اليومي لإرسال المنتجات.'
    ],
    'preview_alt' => [
        'en' => 'Image preview',
        'ar' => 'معاينة الصورة'
    ],
    'upgrade' => [
        'en' => 'Upgrade Plan',
        'ar' => 'ترقية الخطة'
    ],
    'ok' => [
        'en' => 'OK',
        'ar' => 'حسنًا'
    ],

    'empty_product_description' => [
    'en' => 'Product description cannot be empty.',
    'ar' => 'وصف المنتج لا يمكن أن يكون فارغاً.'
],
'image_required' => [
    'en' => 'Main product image is required.',
    'ar' => 'يجب تحميل صورة المنتج الرئيسية.'
],
'image_invalid' => [
    'en' => 'Invalid image format.',
    'ar' => 'تنسيق الصورة غير صالح.'
],
'image_large' => [
    'en' => 'Image size exceeds 2MB.',
    'ar' => 'حجم الصورة يتجاوز 2 ميجابايت.'
],
'upload_failed' => [
    'en' => 'Upload failed. Please try again.',
    'ar' => 'فشل التحميل. يرجى المحاولة مرة أخرى.'
],
'unauthorized' => [
    'en' => 'Unauthorized access.',
    'ar' => 'دخول غير مصرح به.'
],
'product_submitted' => [
    'en' => 'Product submitted successfully!',
    'ar' => 'تم إرسال المنتج بنجاح!'
],
'improve_review' => [
    'en' => 'Please write a more detailed description in your preferred language.',
    'ar' => 'يرجى كتابة وصف أكثر تفصيلاً بلغتك المفضلة.'
],
'suspicious_product_notice' => [
    'en' => 'Your product description may be inauthentic. Please review the content.',
    'ar' => 'وصف المنتج الخاص بك قد يكون غير حقيقي. يرجى مراجعته.'
],
'account_temp_deactivated' => [
    'en' => 'Your account has been temporarily deactivated.',
    'ar' => 'تم تعطيل حسابك مؤقتاً.'
],
'account_permanently_deleted' => [
    'en' => 'Your account has been permanently deleted.',
    'ar' => 'تم حذف حسابك نهائياً.'
],

'suspicious_product_notice' => [
    'en' => 'Your product description may be inauthentic. Please review the content.',
    'ar' => 'وصف المنتج الخاص بك قد يكون غير حقيقي. يرجى مراجعته.'
],

'voucher_already_redeemed' => [
    'en' => 'You have already redeemed this voucher.',
    'ar' => 'لقد قمت بالفعل باسترداد هذا القسيمة.'
],
'voucher_insufficient_points' => [
    'en' => 'You do not have enough points to redeem this voucher.',
    'ar' => 'ليس لديك نقاط كافية لاسترداد هذا القسيمة.'
],

'error' => [
    'en' => 'Error',
    'ar' => 'خطأ'
],
'success' => [
    'en' => 'Success',
    'ar' => 'نجاح'
],
'no_pending_registration' => [
    'en' => 'No pending company registration found.',
    'ar' => 'لم يتم العثور على تسجيل شركة معلق.'
],
'enter_verification_code' => [
    'en' => 'Please enter the verification code.',
    'ar' => 'يرجى إدخال رمز التحقق.'
],
'invalid_verification_code_format' => [
    'en' => 'Invalid code format. Enter a 6-digit number.',
    'ar' => 'صيغة الرمز غير صحيحة. أدخل رقمًا مكونًا من 6 أرقام.'
],
'email_already_exists' => [
    'en' => 'This email is already registered.',
    'ar' => 'هذا البريد الإلكتروني مسجل بالفعل.'
],
'registration_failed' => [
    'en' => 'Registration failed. Please try again later.',
    'ar' => 'فشل التسجيل. يرجى المحاولة لاحقًا.'
],
'wrong_verification_code' => [
    'en' => 'The verification code you entered is incorrect.',
    'ar' => 'رمز التحقق الذي أدخلته غير صحيح.'
],
'account_verified_redirect' => [
    'en' => 'Your company account has been verified. Redirecting...',
    'ar' => 'تم التحقق من حساب شركتك. جارٍ التحويل...'
],

// Verify Company Code Page
'verify_account_title' => [
    'en' => 'Verify Your Account',
    'ar' => 'تحقق من حسابك'
],
'verify_account_description' => [
    'en' => 'Enter the verification code sent to your email',
    'ar' => 'أدخل رمز التحقق المرسل إلى بريدك الإلكتروني'
],
'verification_code_label' => [
    'en' => 'Verification Code',
    'ar' => 'رمز التحقق'
],
'verify_account_button' => [
    'en' => 'Verify Account',
    'ar' => 'تحقق من الحساب'
],
'didnt_receive_code' => [
    'en' => "Didn't receive the code?",
    'ar' => 'لم يصلك الرمز؟'
],
'resend_code' => [
    'en' => 'Resend Code',
    'ar' => 'إعادة إرسال الرمز'
],
'we_sent_code_to' => [
    'en' => 'We sent a 6-digit verification code to',
    'ar' => 'لقد أرسلنا رمز تحقق مكون من 6 أرقام إلى'
],
'go_to_registration' => [
    'en' => 'Go to Registration',
    'ar' => 'اذهب إلى صفحة التسجيل'
],
// From backend validation messages (already added previously)
'error' => [
    'en' => 'Error',
    'ar' => 'خطأ'
],
'success' => [
    'en' => 'Success',
    'ar' => 'نجاح'
],
'no_pending_registration' => [
    'en' => 'No pending company registration found.',
    'ar' => 'لم يتم العثور على تسجيل شركة معلق.'
],
'enter_verification_code' => [
    'en' => 'Please enter the verification code.',
    'ar' => 'يرجى إدخال رمز التحقق.'
],
'invalid_verification_code_format' => [
    'en' => 'Invalid code format. Enter a 6-digit number.',
    'ar' => 'صيغة الرمز غير صحيحة. أدخل رقمًا مكونًا من 6 أرقام.'
],
'email_already_exists' => [
    'en' => 'This email is already registered.',
    'ar' => 'هذا البريد الإلكتروني مسجل بالفعل.'
],
'registration_failed' => [
    'en' => 'Registration failed. Please try again later.',
    'ar' => 'فشل التسجيل. يرجى المحاولة لاحقًا.'
],
'wrong_verification_code' => [
    'en' => 'The verification code you entered is incorrect.',
    'ar' => 'رمز التحقق الذي أدخلته غير صحيح.'
],
'account_verified_redirect' => [
    'en' => 'Your company account has been verified. Redirecting...',
    'ar' => 'تم التحقق من حساب شركتك. جارٍ التحويل...'
],
'reported' => [
    'en' => 'Reported',
    'ar' => 'تم التبليغ'
]


];


// Translation function
if (!function_exists('__')) {
    function __($key)
    {
        global $translations, $lang;
        return $translations[$key][$lang] ?? $key;
    }
}